/**
 * 高中参考数据库种子脚本
 * Seed high school reference data (150+ schools)
 *
 * Usage:
 *   pnpm --filter api ts-node prisma/seed-high-schools.ts
 */

import { PrismaClient, HighSchoolType } from '@prisma/client';
import { computeHsQualityScore } from '@study-abroad/shared/scoring';

const prisma = new PrismaClient();

interface HighSchoolSeed {
  name: string;
  nameZh?: string;
  abbreviation?: string;
  country: string;
  state?: string;
  city?: string;
  type: HighSchoolType;
  tier: number; // 1-5 (5 = top feeder, computed from evaluation dimensions)
  description?: string;
  // Standardized evaluation dimensions (1-5) — optional for skeleton data
  recognition?: number; // AO familiarity
  academicRigor?: number; // Course difficulty, grade deflation
  placementRecord?: number; // Historical placement at top universities
  studentQuality?: number; // Student body competitiveness
  resources?: number; // Counseling, alumni network
  // Supplementary data
  gradeInflation?: 'deflation' | 'neutral' | 'inflation';
  avgSatScore?: number;
  avgIbScore?: number;
  annualTop30Count?: number;
  website?: string;
}

const highSchools: HighSchoolSeed[] = [
  // ============================================
  // US — Boarding Schools (Tier 5)
  // ============================================
  {
    name: 'Phillips Academy Andover',
    nameZh: '菲利普斯安多弗学院',
    abbreviation: 'Andover',
    country: 'US',
    state: 'MA',
    city: 'Andover',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Top boarding school, strong Ivy feeder',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Phillips Exeter Academy',
    nameZh: '菲利普斯埃克塞特学院',
    abbreviation: 'Exeter',
    country: 'US',
    state: 'NH',
    city: 'Exeter',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Elite boarding school, one of the strongest feeders',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: "St. Paul's School",
    nameZh: '圣保罗学校',
    abbreviation: 'SPS',
    country: 'US',
    state: 'NH',
    city: 'Concord',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Historic elite boarding school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Deerfield Academy',
    nameZh: '迪尔菲尔德学院',
    abbreviation: 'Deerfield',
    country: 'US',
    state: 'MA',
    city: 'Deerfield',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Leading New England boarding school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'The Lawrenceville School',
    nameZh: '劳伦斯维尔中学',
    abbreviation: 'Lawrenceville',
    country: 'US',
    state: 'NJ',
    city: 'Lawrenceville',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Top NJ boarding school, strong Princeton feeder',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Choate Rosemary Hall',
    nameZh: '乔特罗斯玛丽中学',
    abbreviation: 'Choate',
    country: 'US',
    state: 'CT',
    city: 'Wallingford',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Top CT boarding school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },

  // US — Boarding Schools (Tier 4)
  {
    name: 'Hotchkiss School',
    nameZh: '霍奇基斯中学',
    abbreviation: 'Hotchkiss',
    country: 'US',
    state: 'CT',
    city: 'Lakeville',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'The Taft School',
    nameZh: '塔夫脱中学',
    abbreviation: 'Taft',
    country: 'US',
    state: 'CT',
    city: 'Watertown',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Loomis Chaffee School',
    nameZh: '鲁米斯查菲中学',
    abbreviation: 'Loomis',
    country: 'US',
    state: 'CT',
    city: 'Windsor',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Groton School',
    nameZh: '格罗顿学校',
    abbreviation: 'Groton',
    country: 'US',
    state: 'MA',
    city: 'Groton',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Middlesex School',
    nameZh: '米德尔塞克斯中学',
    abbreviation: 'Middlesex',
    country: 'US',
    state: 'MA',
    city: 'Concord',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Milton Academy',
    nameZh: '米尔顿学院',
    abbreviation: 'Milton',
    country: 'US',
    state: 'MA',
    city: 'Milton',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Peddie School',
    nameZh: '佩迪中学',
    abbreviation: 'Peddie',
    country: 'US',
    state: 'NJ',
    city: 'Hightstown',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'The Hill School',
    nameZh: '希尔中学',
    abbreviation: 'Hill',
    country: 'US',
    state: 'PA',
    city: 'Pottstown',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Cate School',
    nameZh: '凯特中学',
    abbreviation: 'Cate',
    country: 'US',
    state: 'CA',
    city: 'Carpinteria',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Thacher School',
    nameZh: '撒切尔学校',
    abbreviation: 'Thacher',
    country: 'US',
    state: 'CA',
    city: 'Ojai',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Concord Academy',
    nameZh: '康科德学院',
    abbreviation: 'Concord',
    country: 'US',
    state: 'MA',
    city: 'Concord',
    type: 'BOARDING_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Blair Academy',
    nameZh: '布莱尔学院',
    abbreviation: 'Blair',
    country: 'US',
    state: 'NJ',
    city: 'Blairstown',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Mercersburg Academy',
    nameZh: '摩尔西斯堡学院',
    abbreviation: 'Mercersburg',
    country: 'US',
    state: 'PA',
    city: 'Mercersburg',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Northfield Mount Hermon',
    nameZh: '北野山中学',
    abbreviation: 'NMH',
    country: 'US',
    state: 'MA',
    city: 'Gill',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Tabor Academy',
    nameZh: '泰伯学院',
    abbreviation: 'Tabor',
    country: 'US',
    state: 'MA',
    city: 'Marion',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Kent School',
    nameZh: '肯特学校',
    abbreviation: 'Kent',
    country: 'US',
    state: 'CT',
    city: 'Kent',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Pomfret School',
    nameZh: '庞弗雷特中学',
    abbreviation: 'Pomfret',
    country: 'US',
    state: 'CT',
    city: 'Pomfret',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Westminster School',
    nameZh: '威斯敏斯特学校',
    country: 'US',
    state: 'CT',
    city: 'Simsbury',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Emma Willard School',
    nameZh: '艾玛威拉德女校',
    abbreviation: 'Emma Willard',
    country: 'US',
    state: 'NY',
    city: 'Troy',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: "Miss Porter's School",
    nameZh: '波特女子学校',
    abbreviation: "Miss Porter's",
    country: 'US',
    state: 'CT',
    city: 'Farmington',
    type: 'BOARDING_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },

  // ============================================
  // US — Top Day Schools (Public Magnets & Private)
  // ============================================
  {
    name: 'Thomas Jefferson High School for Science and Technology',
    nameZh: '托马斯·杰斐逊科技高中',
    abbreviation: 'TJHSST',
    country: 'US',
    state: 'VA',
    city: 'Alexandria',
    type: 'PUBLIC_US',
    tier: 5,
    description: '#1 public high school in the US',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 3,
    gradeInflation: 'deflation',
  },
  {
    name: 'Stuyvesant High School',
    nameZh: '史岱文森高中',
    abbreviation: 'Stuy',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PUBLIC_US',
    tier: 5,
    description: 'Elite NYC specialized high school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 3,
    gradeInflation: 'deflation',
  },
  {
    name: 'Bronx High School of Science',
    nameZh: '布朗克斯科学高中',
    abbreviation: 'Bronx Science',
    country: 'US',
    state: 'NY',
    city: 'Bronx',
    type: 'PUBLIC_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Brooklyn Technical High School',
    nameZh: '布鲁克林技术高中',
    abbreviation: 'Brooklyn Tech',
    country: 'US',
    state: 'NY',
    city: 'Brooklyn',
    type: 'PUBLIC_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Illinois Mathematics and Science Academy',
    nameZh: '伊利诺伊数学与科学学院',
    abbreviation: 'IMSA',
    country: 'US',
    state: 'IL',
    city: 'Aurora',
    type: 'PUBLIC_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'North Carolina School of Science and Mathematics',
    nameZh: '北卡科学与数学学校',
    abbreviation: 'NCSSM',
    country: 'US',
    state: 'NC',
    city: 'Durham',
    type: 'PUBLIC_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Massachusetts Academy of Math and Science',
    nameZh: '麻省数学与科学学院',
    abbreviation: 'Mass Academy',
    country: 'US',
    state: 'MA',
    city: 'Worcester',
    type: 'PUBLIC_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Basis Scottsdale',
    nameZh: 'Basis斯科茨代尔',
    country: 'US',
    state: 'AZ',
    city: 'Scottsdale',
    type: 'PUBLIC_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 2,
    gradeInflation: 'neutral',
  },
  {
    name: 'Whitney High School',
    nameZh: '惠特尼高中',
    country: 'US',
    state: 'CA',
    city: 'Cerritos',
    type: 'PUBLIC_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 2,
    gradeInflation: 'neutral',
  },

  // US — Top Private Day Schools
  {
    name: 'Trinity School',
    nameZh: '三一学校',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 5,
    description: 'Top NYC private school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Collegiate School',
    nameZh: '学院学校',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Horace Mann School',
    nameZh: '霍瑞斯曼中学',
    abbreviation: 'Horace Mann',
    country: 'US',
    state: 'NY',
    city: 'Bronx',
    type: 'PRIVATE_US',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Dalton School',
    nameZh: '道尔顿学校',
    abbreviation: 'Dalton',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Harvard-Westlake School',
    nameZh: '哈佛西湖学校',
    abbreviation: 'HW',
    country: 'US',
    state: 'CA',
    city: 'Los Angeles',
    type: 'PRIVATE_US',
    tier: 5,
    description: 'Top LA private school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'The College Preparatory School',
    nameZh: '大学预备学校',
    abbreviation: 'College Prep',
    country: 'US',
    state: 'CA',
    city: 'Oakland',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Lakeside School',
    nameZh: '湖滨学校',
    abbreviation: 'Lakeside',
    country: 'US',
    state: 'WA',
    city: 'Seattle',
    type: 'PRIVATE_US',
    tier: 4,
    description: 'Top Seattle private school (Bill Gates alma mater)',
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Sidwell Friends School',
    nameZh: '西德威尔友谊中学',
    abbreviation: 'Sidwell',
    country: 'US',
    state: 'DC',
    city: 'Washington',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Brearley School',
    nameZh: '布里尔利学校',
    abbreviation: 'Brearley',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Spence School',
    nameZh: '斯宾塞学校',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Roxbury Latin School',
    nameZh: '罗克斯伯里拉丁学校',
    abbreviation: 'Roxbury Latin',
    country: 'US',
    state: 'MA',
    city: 'West Roxbury',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Noble and Greenough School',
    nameZh: '诺贝尔和格里诺学校',
    abbreviation: 'Nobles',
    country: 'US',
    state: 'MA',
    city: 'Dedham',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Winsor School',
    nameZh: '温莎学校',
    country: 'US',
    state: 'MA',
    city: 'Boston',
    type: 'PRIVATE_US',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Germantown Friends School',
    nameZh: '日耳曼敦友谊学校',
    country: 'US',
    state: 'PA',
    city: 'Philadelphia',
    type: 'PRIVATE_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Menlo School',
    nameZh: '门罗学校',
    country: 'US',
    state: 'CA',
    city: 'Atherton',
    type: 'PRIVATE_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Crystal Springs Uplands School',
    nameZh: '水晶泉高地学校',
    country: 'US',
    state: 'CA',
    city: 'Hillsborough',
    type: 'PRIVATE_US',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },

  // ============================================
  // China — International Schools / Programs (Tier 5)
  // ============================================
  {
    name: 'Shanghai High School International Division',
    nameZh: '上海中学国际部',
    abbreviation: 'SHSID',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: '中国顶级国际学校，Ivy 强 feeder',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Shenzhen College of International Education',
    nameZh: '深圳国际交流学院',
    abbreviation: 'SCIE',
    country: 'CN',
    state: '广东',
    city: '深圳',
    type: 'INTL_CN',
    tier: 5,
    description: 'A-Level 体系顶级学校，牛剑/Ivy 录取突出',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'Beijing National Day School',
    nameZh: '北京十一学校国际部',
    abbreviation: 'BNDS',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'The Affiliated High School of Peking University',
    nameZh: '北大附中国际部',
    abbreviation: 'PKUHS',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'The High School Affiliated to Renmin University of China',
    nameZh: '人大附中国际部',
    abbreviation: 'RDFZ ICC',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 5,
    description: '北京顶级国际课程中心',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
    gradeInflation: 'deflation',
  },
  {
    name: 'UWC Changshu China',
    nameZh: '世界联合学院常熟',
    abbreviation: 'UWC常熟',
    country: 'CN',
    state: '江苏',
    city: '常熟',
    type: 'INTL_CN',
    tier: 5,
    description: 'UWC 体系中国校区',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
    gradeInflation: 'deflation',
  },

  // China — International Schools (Tier 4)
  {
    name: 'The Experimental High School Attached to Beijing Normal University',
    nameZh: '北师大实验中学国际部',
    abbreviation: 'BNUEHSID',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Nanjing Foreign Language School',
    nameZh: '南京外国语学校',
    abbreviation: 'NFLS',
    country: 'CN',
    state: '江苏',
    city: '南京',
    type: 'INTL_CN',
    tier: 4,
    description: '南京顶级外语特色学校',
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Shanghai World Foreign Language Academy',
    nameZh: '上海世界外国语中学',
    abbreviation: 'WFLA',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Shanghai Pinghe Bilingual School',
    nameZh: '上海平和双语学校',
    abbreviation: 'Pinghe',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Dulwich College Shanghai Pudong',
    nameZh: '上海德威英国国际学校浦东校区',
    abbreviation: 'Dulwich SH',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Shanghai American School',
    nameZh: '上海美国学校',
    abbreviation: 'SAS',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },

  // ============================================
  // CN — Shanghai Skeleton Schools (Tier ranking data, no evaluation dimensions)
  // Grade D quality → hsImpactEnabled=false → safe for predictions
  // ============================================

  // --- Tier 5 (第一梯队) ---
  {
    name: 'YK Pao School',
    nameZh: '包玉刚实验学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: 'IB课程体系，上海顶级民办双语学校',
  },
  {
    name: 'Starriver Bilingual School',
    nameZh: '星河湾双语学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: 'IB/中美融合课程，上海一梯队学校',
  },
  {
    name: 'SJTU Affiliated High School IB Centre',
    nameZh: '交大附中IB课程中心',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 5,
    description: 'IB课程体系，依托交大附中',
  },
  {
    name: 'WLSA Shanghai Academy',
    nameZh: 'WLSA上海学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: 'IB/AP/美高课程，世界名中学联盟成员',
  },
  {
    name: 'Ulink College Shanghai',
    nameZh: '领科教育上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: 'A-Level/IB课程，英国方向顶尖',
  },
  {
    name: 'Guanghua Cambridge International School',
    nameZh: '光华剑桥',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: 'A-Level课程体系，牛剑录取突出',
  },

  // --- Tier 4 (第二梯队) ---
  {
    name: 'Shanghai Qibao Dwight High School',
    nameZh: '七宝德怀特高级中学',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB课程，中美合办',
  },
  {
    name: 'Shanghai United International School',
    nameZh: '协和双语高级中学',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB/AP/A-Level多课程体系',
  },
  {
    name: 'Shanghai Xiwai International School',
    nameZh: '西南位育中学国际部',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'AP课程体系',
  },
  {
    name: 'Shanghai Weiyu High School International',
    nameZh: '民办位育中学',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB/A-Level课程体系',
  },
  {
    name: 'SISU Affiliated High School',
    nameZh: '上海外国语大学附属外国语学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 4,
    description: '上外附中，语言特色突出',
  },
  {
    name: 'Fudan Affiliated High School International Division',
    nameZh: '复旦附中国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 4,
    description: 'IB课程体系，依托复旦附中',
  },
  {
    name: 'ECNU No.2 Affiliated High School Zizhu International',
    nameZh: '华二紫竹国际学院',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB/A-Level/AP课程，华二系',
  },
  {
    name: 'SMIC Private School',
    nameZh: '中芯国际学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'AP课程体系，中芯集团创办',
  },
  {
    name: 'Yew Wah International Education School Shanghai',
    nameZh: '耀华国际教育学校上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'A-Level/IGCSE课程体系',
  },
  {
    name: 'Shanghai Wenlai High School',
    nameZh: '文来中学国际部',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'AP/美高课程体系',
  },
  {
    name: 'ECNU No.2 Affiliated High School International Division',
    nameZh: '华师大二附中国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 4,
    description: 'AP课程体系，上海四大名校',
  },
  {
    name: 'Shanghai Nanyang Model High School International',
    nameZh: '南洋模范中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 4,
    description: 'BC课程体系，百年名校',
  },
  {
    name: 'Shanghai Jianping High School International Division',
    nameZh: '建平中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 4,
    description: 'AP课程体系，浦东名校',
  },
  {
    name: 'SISU Cambridge A-Level Centre',
    nameZh: '上实剑桥国际高中',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'A-Level/AP课程体系',
  },
  {
    name: 'Shanghai Concord Bilingual School',
    nameZh: '康德双语实验学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'A-Level课程体系',
  },
  {
    name: 'Shanghai Gaoteng Academy',
    nameZh: '高藤致远创新学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'AP课程体系',
  },
  {
    name: 'Shanghai Caoyang No.2 High School International',
    nameZh: '曹杨二中国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 4,
    description: 'PGA/AP课程体系',
  },
  {
    name: 'Vanke DTD School Shanghai',
    nameZh: '万科德英乐学院',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'A-Level/AP课程体系',
  },
  {
    name: 'Shanghai Tianjibing High School',
    nameZh: '田家炳中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PRIVATE_CN',
    tier: 4,
    description: 'AP课程体系',
  },
  {
    name: 'Shanghai Nuoda Academy',
    nameZh: '诺达双语学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB/AP课程体系',
  },

  // --- Tier 3 (第三梯队) ---
  {
    name: 'Shanghai Shixi High School International',
    nameZh: '市西中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 3,
    description: 'IB课程体系',
  },
  {
    name: 'Guanghua Qidi International School',
    nameZh: '光华启迪',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'A-Level课程体系，个性化教学',
  },
  {
    name: 'Shanghai YINGAOMU Academy',
    nameZh: '英澳美国际学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'A-Level/VCE/DSE课程体系',
  },
  {
    name: 'Adcote School Shanghai',
    nameZh: '阿德科特学校上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'A-Level/IB课程体系，英国阿德科特分校',
  },
  {
    name: 'Shanghai Shangde Bilingual School',
    nameZh: '尚德实验学校国际部',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'IB课程体系',
  },
  {
    name: 'Shanghai Wenqi Huidian School',
    nameZh: '文绮汇点美高',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'AP/美高课程体系',
  },
  {
    name: 'Shanghai United Jiaoke International',
    nameZh: '协和教科实验中学国际部',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'BC/AP课程体系',
  },
  {
    name: 'Shanghai Demin International School',
    nameZh: '民办德闵学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'A-Level课程体系',
  },
  {
    name: 'Shanghai Hongrun Boyuan School',
    nameZh: '宏润博源学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'AP/美高课程体系',
  },
  {
    name: 'Shanghai Maple Leaf International School',
    nameZh: '枫叶国际学校上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'BC课程体系',
  },
  {
    name: 'Shanghai Keqiao Academy',
    nameZh: '科桥教育',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'A-Level课程体系',
  },
  {
    name: 'Shanghai LWS Academy',
    nameZh: '美高学校上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'AP/美高课程体系',
  },
  {
    name: 'Wellington College International Shanghai',
    nameZh: '上海惠灵顿国际学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 3,
    description: 'IB/A-Level课程体系，英国惠灵顿公学分校',
  },

  // --- Tier 2 (第四梯队) ---
  {
    name: 'Shanghai Gezhi High School International',
    nameZh: '格致中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 2,
    description: 'AP课程体系',
  },
  {
    name: 'HD Shanghai School',
    nameZh: '赫贤学校上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'A-Level/IB课程体系',
  },
  {
    name: 'Shanghai Datong High School International',
    nameZh: '大同中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 2,
    description: 'PGA课程体系',
  },
  {
    name: 'Shanghai NorthAm Academy',
    nameZh: '诺美学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'AP/美高课程体系',
  },
  {
    name: 'Shanghai Norco International School',
    nameZh: '诺科学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'A-Level/AP课程体系',
  },
  {
    name: 'Shanghai Luwan High School International',
    nameZh: '卢湾高级中学国际课程班',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'PUBLIC_CN',
    tier: 2,
    description: 'BC课程体系',
  },
  {
    name: 'Shanghai MacDuffie International School',
    nameZh: '美达菲学校上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'IB/AP课程体系',
  },
  {
    name: 'Shanghai Huading Academy',
    nameZh: '华鼎书院',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'AP课程体系',
  },
  {
    name: 'Cardiff Sixth Form College Shanghai',
    nameZh: '卡迪夫公学上海校区',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'A-Level课程体系，英国卡迪夫分校',
  },
  {
    name: 'Shanghai Xinjiyuan Shuangyu School',
    nameZh: '新纪元双语学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 2,
    description: 'AP/美高课程体系',
  },

  // --- Tier 1 (第五梯队) ---
  {
    name: 'SISU Xiwai International School',
    nameZh: '上外西外外国语学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 1,
    description: 'AP课程体系',
  },
  {
    name: 'Shanghai Golden Apple Bilingual School',
    nameZh: '金苹果双语学校国际部',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 1,
    description: 'AP/A-Level课程体系',
  },
  {
    name: 'Shanghai Liaoyuan Bilingual School',
    nameZh: '燎原双语学校国际部',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 1,
    description: 'IB/BC课程体系',
  },
  {
    name: 'Shanghai Ivy League School',
    nameZh: '常青藤学校',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 1,
    description: 'AP课程体系',
  },

  {
    name: 'Beijing Shidi High School International Department',
    nameZh: '北京师大附中国际部',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Wuxi Big Bridge Academy',
    nameZh: '无锡大桥实验学校',
    abbreviation: 'Big Bridge',
    country: 'CN',
    state: '江苏',
    city: '无锡',
    type: 'INTL_CN',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Suzhou Foreign Language School',
    nameZh: '苏州外国语学校',
    abbreviation: 'SFLS',
    country: 'CN',
    state: '江苏',
    city: '苏州',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: "The High School Affiliated to Xi'an Jiaotong University",
    nameZh: '西安交大附中国际部',
    country: 'CN',
    state: '陕西',
    city: '西安',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Guangzhou Foreign Language School',
    nameZh: '广州外国语学校',
    abbreviation: 'GZFLS',
    country: 'CN',
    state: '广东',
    city: '广州',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Shenzhen Middle School International System',
    nameZh: '深圳中学国际体系',
    abbreviation: 'SZMS Intl',
    country: 'CN',
    state: '广东',
    city: '深圳',
    type: 'INTL_CN',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Hangzhou Foreign Languages School',
    nameZh: '杭州外国语学校',
    abbreviation: 'HFLS',
    country: 'CN',
    state: '浙江',
    city: '杭州',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Chengdu Shude High School International Department',
    nameZh: '成都树德中学国际部',
    country: 'CN',
    state: '四川',
    city: '成都',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Beijing World Youth Academy',
    nameZh: '北京世青国际学校',
    abbreviation: 'BWYA',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Keystone Academy',
    nameZh: '北京鼎石学校',
    abbreviation: 'Keystone',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB 体系顶级寄宿学校',
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Beijing Huijia Private School',
    nameZh: '北京汇佳私立学校',
    abbreviation: 'Huijia',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },

  // China — Public Schools (High Overseas Admission) (Tier 3-4)
  {
    name: 'The Affiliated High School of South China Normal University',
    nameZh: '华南师大附中',
    abbreviation: 'SCNUAHS',
    country: 'CN',
    state: '广东',
    city: '广州',
    type: 'PUBLIC_CN',
    tier: 3,
    recognition: 2,
    academicRigor: 4,
    placementRecord: 2,
    studentQuality: 4,
    resources: 2,
    gradeInflation: 'neutral',
  },
  {
    name: 'Chengdu No.7 High School',
    nameZh: '成都七中',
    country: 'CN',
    state: '四川',
    city: '成都',
    type: 'PUBLIC_CN',
    tier: 3,
    recognition: 2,
    academicRigor: 4,
    placementRecord: 2,
    studentQuality: 4,
    resources: 2,
    gradeInflation: 'neutral',
  },
  {
    name: 'Wuhan Foreign Languages School',
    nameZh: '武汉外国语学校',
    abbreviation: 'WFLS',
    country: 'CN',
    state: '湖北',
    city: '武汉',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },
  {
    name: 'Changsha Yali High School International Department',
    nameZh: '长沙雅礼中学国际部',
    country: 'CN',
    state: '湖南',
    city: '长沙',
    type: 'INTL_CN',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
    gradeInflation: 'neutral',
  },

  // ============================================
  // Singapore
  // ============================================
  {
    name: 'Raffles Institution',
    nameZh: '莱佛士书院',
    abbreviation: 'RI',
    country: 'SG',
    city: 'Singapore',
    type: 'PUBLIC_OTHER',
    tier: 5,
    description: "Singapore's top school, strong Ivy/Oxbridge feeder",
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 4,
  },
  {
    name: 'Hwa Chong Institution',
    nameZh: '华侨中学',
    abbreviation: 'HCI',
    country: 'SG',
    city: 'Singapore',
    type: 'PUBLIC_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'NUS High School of Math and Science',
    nameZh: '新加坡国大数理中学',
    abbreviation: 'NUS High',
    country: 'SG',
    city: 'Singapore',
    type: 'PUBLIC_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'Anglo-Chinese School (Independent)',
    nameZh: '英华自主中学',
    abbreviation: 'ACS(I)',
    country: 'SG',
    city: 'Singapore',
    type: 'PRIVATE_OTHER',
    tier: 3,
    recognition: 3,
    academicRigor: 3,
    placementRecord: 3,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: 'United World College of South East Asia',
    nameZh: 'UWC东南亚',
    abbreviation: 'UWCSEA',
    country: 'SG',
    city: 'Singapore',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },

  // ============================================
  // United Kingdom
  // ============================================
  {
    name: 'Eton College',
    nameZh: '伊顿公学',
    abbreviation: 'Eton',
    country: 'GB',
    state: 'Berkshire',
    city: 'Windsor',
    type: 'PRIVATE_OTHER',
    tier: 5,
    description: 'The most prestigious British public school',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Westminster School',
    nameZh: '威斯敏斯特公学',
    abbreviation: 'Westminster UK',
    country: 'GB',
    state: 'London',
    city: 'London',
    type: 'PRIVATE_OTHER',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: "St Paul's School",
    nameZh: '圣保罗学校',
    abbreviation: "St Paul's UK",
    country: 'GB',
    state: 'London',
    city: 'London',
    type: 'PRIVATE_OTHER',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Winchester College',
    nameZh: '温切斯特公学',
    abbreviation: 'Winchester',
    country: 'GB',
    state: 'Hampshire',
    city: 'Winchester',
    type: 'PRIVATE_OTHER',
    tier: 5,
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
    gradeInflation: 'deflation',
  },
  {
    name: 'Harrow School',
    nameZh: '哈罗公学',
    abbreviation: 'Harrow',
    country: 'GB',
    state: 'London',
    city: 'Harrow',
    type: 'PRIVATE_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Rugby School',
    nameZh: '拉格比公学',
    abbreviation: 'Rugby',
    country: 'GB',
    state: 'Warwickshire',
    city: 'Rugby',
    type: 'PRIVATE_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Charterhouse',
    nameZh: '切特豪斯公学',
    country: 'GB',
    state: 'Surrey',
    city: 'Godalming',
    type: 'PRIVATE_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },
  {
    name: 'Sevenoaks School',
    nameZh: '七橡树中学',
    abbreviation: 'Sevenoaks',
    country: 'GB',
    state: 'Kent',
    city: 'Sevenoaks',
    type: 'PRIVATE_OTHER',
    tier: 4,
    description: 'Top IB school in the UK',
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
    gradeInflation: 'neutral',
  },

  // ============================================
  // Canada
  // ============================================
  {
    name: 'Upper Canada College',
    nameZh: '上加拿大学院',
    abbreviation: 'UCC',
    country: 'CA',
    state: 'ON',
    city: 'Toronto',
    type: 'PRIVATE_OTHER',
    tier: 4,
    recognition: 3,
    academicRigor: 4,
    placementRecord: 3,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'Appleby College',
    nameZh: '亚比利学院',
    abbreviation: 'Appleby',
    country: 'CA',
    state: 'ON',
    city: 'Oakville',
    type: 'PRIVATE_OTHER',
    tier: 4,
    recognition: 3,
    academicRigor: 4,
    placementRecord: 3,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'Crescent School',
    nameZh: '新月学校',
    country: 'CA',
    state: 'ON',
    city: 'Toronto',
    type: 'PRIVATE_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: 'Havergal College',
    nameZh: '海福格尔学院',
    country: 'CA',
    state: 'ON',
    city: 'Toronto',
    type: 'PRIVATE_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: "St. Andrew's College",
    nameZh: '圣安德鲁学院',
    country: 'CA',
    state: 'ON',
    city: 'Aurora',
    type: 'PRIVATE_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },

  // ============================================
  // Other Countries
  // ============================================
  {
    name: 'Seoul International School',
    nameZh: '首尔国际学校',
    abbreviation: 'SIS',
    country: 'KR',
    city: 'Seoul',
    type: 'INTL_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: 'Korea International School',
    nameZh: '韩国国际学校',
    abbreviation: 'KIS',
    country: 'KR',
    city: 'Seoul',
    type: 'INTL_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: 'International School Bangkok',
    nameZh: '曼谷国际学校',
    abbreviation: 'ISB',
    country: 'TH',
    city: 'Bangkok',
    type: 'INTL_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: 'Hong Kong International School',
    nameZh: '香港国际学校',
    abbreviation: 'HKIS',
    country: 'HK',
    city: 'Hong Kong',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'Chinese International School',
    nameZh: '汉基国际学校',
    abbreviation: 'CIS',
    country: 'HK',
    city: 'Hong Kong',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'Li Po Chun United World College',
    nameZh: '李宝椿联合世界书院',
    abbreviation: 'LPC UWC',
    country: 'HK',
    city: 'Hong Kong',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'UWC Atlantic College',
    nameZh: 'UWC大西洋学院',
    abbreviation: 'UWC Atlantic',
    country: 'GB',
    state: 'Wales',
    city: 'Llantwit Major',
    type: 'INTL_OTHER',
    tier: 5,
    description: 'The original UWC campus',
    recognition: 5,
    academicRigor: 5,
    placementRecord: 5,
    studentQuality: 5,
    resources: 5,
  },
  {
    name: 'UWC Pearson College',
    nameZh: 'UWC皮尔逊学院',
    abbreviation: 'UWC Pearson',
    country: 'CA',
    state: 'BC',
    city: 'Victoria',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },
  {
    name: 'UWC Robert Bosch College',
    nameZh: 'UWC罗伯特·博世学院',
    abbreviation: 'UWC RBC',
    country: 'DE',
    city: 'Freiburg',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },

  // ============================================
  // India
  // ============================================
  {
    name: 'Doon School',
    nameZh: '杜恩学校',
    abbreviation: 'Doon',
    country: 'IN',
    state: 'Uttarakhand',
    city: 'Dehradun',
    type: 'PRIVATE_OTHER',
    tier: 4,
    recognition: 3,
    academicRigor: 4,
    placementRecord: 3,
    studentQuality: 4,
    resources: 3,
  },
  {
    name: 'Woodstock School',
    nameZh: '伍德斯托克学校',
    country: 'IN',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    type: 'INTL_OTHER',
    tier: 3,
    recognition: 2,
    academicRigor: 3,
    placementRecord: 2,
    studentQuality: 3,
    resources: 3,
  },
  {
    name: 'Mahindra UWC India',
    nameZh: 'UWC印度马恒达学院',
    abbreviation: 'UWC India',
    country: 'IN',
    state: 'Maharashtra',
    city: 'Pune',
    type: 'INTL_OTHER',
    tier: 4,
    recognition: 4,
    academicRigor: 4,
    placementRecord: 4,
    studentQuality: 4,
    resources: 4,
  },

  // ============================================
  // Japan
  // ============================================
  {
    name: 'ISAK Japan',
    nameZh: 'ISAK日本国际学校',
    abbreviation: 'UWC ISAK',
    country: 'JP',
    state: 'Nagano',
    city: 'Karuizawa',
    type: 'INTL_OTHER',
    tier: 4,
    description: 'UWC member school in Japan',
    recognition: 3,
    academicRigor: 4,
    placementRecord: 3,
    studentQuality: 4,
    resources: 4,
  },
];

async function seedHighSchools() {
  console.log('🏫 Seeding high school reference data...');

  let created = 0;
  let updated = 0;

  for (const hs of highSchools) {
    const hasDimensions = !!(
      hs.recognition ||
      hs.academicRigor ||
      hs.placementRecord ||
      hs.studentQuality ||
      hs.resources
    );

    // Compute quality score (since we bypass HighSchoolService.beforeSave)
    const quality = computeHsQualityScore({
      name: hs.name,
      country: hs.country,
      type: hs.type,
      state: hs.state,
      city: hs.city,
      nameZh: hs.nameZh,
      tier: hs.tier,
      recognition: hs.recognition,
      academicRigor: hs.academicRigor,
      placementRecord: hs.placementRecord,
      studentQuality: hs.studentQuality,
      resources: hs.resources,
      gradeInflation: hs.gradeInflation,
      evaluatedBy: hasDimensions ? 'system' : undefined,
      website: hs.website,
      avgSatScore: hs.avgSatScore,
      avgIbScore: hs.avgIbScore,
    });

    const existing = hs.abbreviation
      ? await prisma.highSchool.findUnique({
          where: { abbreviation: hs.abbreviation },
        })
      : await prisma.highSchool.findUnique({
          where: {
            name_country_state: {
              name: hs.name,
              country: hs.country,
              state: hs.state || '',
            },
          },
        });

    if (existing) {
      // For skeleton data: only update tier, nameZh, description — preserve existing evaluations
      // For complete data: update everything
      const updateData: Record<string, any> = hasDimensions
        ? {
            ...hs,
            qualityScore: quality.score,
            qualityGrade: quality.grade,
            hsImpactEnabled: quality.grade !== 'D',
            evaluatedAt: new Date(),
            evaluatedBy: 'system',
          }
        : {
            nameZh: hs.nameZh,
            tier: hs.tier,
            description: hs.description,
            // Only update quality fields if existing has no evaluations
            ...(existing.recognition
              ? {}
              : {
                  qualityScore: quality.score,
                  qualityGrade: quality.grade,
                  hsImpactEnabled: quality.grade !== 'D',
                }),
          };

      await prisma.highSchool.update({
        where: { id: existing.id },
        data: updateData,
      });
      updated++;
    } else {
      await prisma.highSchool.create({
        data: {
          ...hs,
          qualityScore: quality.score,
          qualityGrade: quality.grade,
          hsImpactEnabled: quality.grade !== 'D',
          evaluatedAt: hasDimensions ? new Date() : null,
          evaluatedBy: hasDimensions ? 'system' : null,
        },
      });
      created++;
    }
  }

  console.log(
    `✅ High schools seeded: ${created} created, ${updated} updated (total: ${highSchools.length})`,
  );
}

// Direct execution
seedHighSchools()
  .catch((e) => {
    console.error('❌ High school seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());

export { seedHighSchools, highSchools };
