/**
 * 高中参考数据库种子脚本
 * Seed high school reference data (150+ schools)
 *
 * Usage:
 *   pnpm --filter api ts-node prisma/seed-high-schools.ts
 */

import { PrismaClient, HighSchoolType } from '@prisma/client';

const prisma = new PrismaClient();

interface HighSchoolSeed {
  name: string;
  nameZh?: string;
  abbreviation?: string;
  country: string;
  state?: string;
  city?: string;
  type: HighSchoolType;
  tier: number; // 1-5 (5 = top feeder)
  description?: string;
}

const highSchools: HighSchoolSeed[] = [
  // ============================================
  // US — Boarding Schools (Tier 5)
  // ============================================
  {
    name: 'Phillips Academy Andover',
    nameZh: '菲利普斯安多弗学院',
    abbreviation: 'Andover',
    country: 'US',
    state: 'MA',
    city: 'Andover',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Top boarding school, strong Ivy feeder',
  },
  {
    name: 'Phillips Exeter Academy',
    nameZh: '菲利普斯埃克塞特学院',
    abbreviation: 'Exeter',
    country: 'US',
    state: 'NH',
    city: 'Exeter',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Elite boarding school, one of the strongest feeders',
  },
  {
    name: "St. Paul's School",
    nameZh: '圣保罗学校',
    abbreviation: 'SPS',
    country: 'US',
    state: 'NH',
    city: 'Concord',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Historic elite boarding school',
  },
  {
    name: 'Deerfield Academy',
    nameZh: '迪尔菲尔德学院',
    abbreviation: 'Deerfield',
    country: 'US',
    state: 'MA',
    city: 'Deerfield',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Leading New England boarding school',
  },
  {
    name: 'The Lawrenceville School',
    nameZh: '劳伦斯维尔中学',
    abbreviation: 'Lawrenceville',
    country: 'US',
    state: 'NJ',
    city: 'Lawrenceville',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Top NJ boarding school, strong Princeton feeder',
  },
  {
    name: 'Choate Rosemary Hall',
    nameZh: '乔特罗斯玛丽中学',
    abbreviation: 'Choate',
    country: 'US',
    state: 'CT',
    city: 'Wallingford',
    type: 'BOARDING_US',
    tier: 5,
    description: 'Top CT boarding school',
  },

  // US — Boarding Schools (Tier 4)
  {
    name: 'Hotchkiss School',
    nameZh: '霍奇基斯中学',
    abbreviation: 'Hotchkiss',
    country: 'US',
    state: 'CT',
    city: 'Lakeville',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'The Taft School',
    nameZh: '塔夫脱中学',
    abbreviation: 'Taft',
    country: 'US',
    state: 'CT',
    city: 'Watertown',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Loomis Chaffee School',
    nameZh: '鲁米斯查菲中学',
    abbreviation: 'Loomis',
    country: 'US',
    state: 'CT',
    city: 'Windsor',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Groton School',
    nameZh: '格罗顿学校',
    abbreviation: 'Groton',
    country: 'US',
    state: 'MA',
    city: 'Groton',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Middlesex School',
    nameZh: '米德尔塞克斯中学',
    abbreviation: 'Middlesex',
    country: 'US',
    state: 'MA',
    city: 'Concord',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Milton Academy',
    nameZh: '米尔顿学院',
    abbreviation: 'Milton',
    country: 'US',
    state: 'MA',
    city: 'Milton',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Peddie School',
    nameZh: '佩迪中学',
    abbreviation: 'Peddie',
    country: 'US',
    state: 'NJ',
    city: 'Hightstown',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'The Hill School',
    nameZh: '希尔中学',
    abbreviation: 'Hill',
    country: 'US',
    state: 'PA',
    city: 'Pottstown',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Cate School',
    nameZh: '凯特中学',
    abbreviation: 'Cate',
    country: 'US',
    state: 'CA',
    city: 'Carpinteria',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Thacher School',
    nameZh: '撒切尔学校',
    abbreviation: 'Thacher',
    country: 'US',
    state: 'CA',
    city: 'Ojai',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Concord Academy',
    nameZh: '康科德学院',
    abbreviation: 'Concord',
    country: 'US',
    state: 'MA',
    city: 'Concord',
    type: 'BOARDING_US',
    tier: 4,
  },
  {
    name: 'Blair Academy',
    nameZh: '布莱尔学院',
    abbreviation: 'Blair',
    country: 'US',
    state: 'NJ',
    city: 'Blairstown',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Mercersburg Academy',
    nameZh: '摩尔西斯堡学院',
    abbreviation: 'Mercersburg',
    country: 'US',
    state: 'PA',
    city: 'Mercersburg',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Northfield Mount Hermon',
    nameZh: '北野山中学',
    abbreviation: 'NMH',
    country: 'US',
    state: 'MA',
    city: 'Gill',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Tabor Academy',
    nameZh: '泰伯学院',
    abbreviation: 'Tabor',
    country: 'US',
    state: 'MA',
    city: 'Marion',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Kent School',
    nameZh: '肯特学校',
    abbreviation: 'Kent',
    country: 'US',
    state: 'CT',
    city: 'Kent',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Pomfret School',
    nameZh: '庞弗雷特中学',
    abbreviation: 'Pomfret',
    country: 'US',
    state: 'CT',
    city: 'Pomfret',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Westminster School',
    nameZh: '威斯敏斯特学校',
    country: 'US',
    state: 'CT',
    city: 'Simsbury',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: 'Emma Willard School',
    nameZh: '艾玛威拉德女校',
    abbreviation: 'Emma Willard',
    country: 'US',
    state: 'NY',
    city: 'Troy',
    type: 'BOARDING_US',
    tier: 3,
  },
  {
    name: "Miss Porter's School",
    nameZh: '波特女子学校',
    abbreviation: "Miss Porter's",
    country: 'US',
    state: 'CT',
    city: 'Farmington',
    type: 'BOARDING_US',
    tier: 3,
  },

  // ============================================
  // US — Top Day Schools (Public Magnets & Private)
  // ============================================
  {
    name: 'Thomas Jefferson High School for Science and Technology',
    nameZh: '托马斯·杰斐逊科技高中',
    abbreviation: 'TJHSST',
    country: 'US',
    state: 'VA',
    city: 'Alexandria',
    type: 'PUBLIC_US',
    tier: 5,
    description: '#1 public high school in the US',
  },
  {
    name: 'Stuyvesant High School',
    nameZh: '史岱文森高中',
    abbreviation: 'Stuy',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PUBLIC_US',
    tier: 5,
    description: 'Elite NYC specialized high school',
  },
  {
    name: 'Bronx High School of Science',
    nameZh: '布朗克斯科学高中',
    abbreviation: 'Bronx Science',
    country: 'US',
    state: 'NY',
    city: 'Bronx',
    type: 'PUBLIC_US',
    tier: 4,
  },
  {
    name: 'Brooklyn Technical High School',
    nameZh: '布鲁克林技术高中',
    abbreviation: 'Brooklyn Tech',
    country: 'US',
    state: 'NY',
    city: 'Brooklyn',
    type: 'PUBLIC_US',
    tier: 4,
  },
  {
    name: 'Illinois Mathematics and Science Academy',
    nameZh: '伊利诺伊数学与科学学院',
    abbreviation: 'IMSA',
    country: 'US',
    state: 'IL',
    city: 'Aurora',
    type: 'PUBLIC_US',
    tier: 4,
  },
  {
    name: 'North Carolina School of Science and Mathematics',
    nameZh: '北卡科学与数学学校',
    abbreviation: 'NCSSM',
    country: 'US',
    state: 'NC',
    city: 'Durham',
    type: 'PUBLIC_US',
    tier: 4,
  },
  {
    name: 'Massachusetts Academy of Math and Science',
    nameZh: '麻省数学与科学学院',
    abbreviation: 'Mass Academy',
    country: 'US',
    state: 'MA',
    city: 'Worcester',
    type: 'PUBLIC_US',
    tier: 4,
  },
  {
    name: 'Basis Scottsdale',
    nameZh: 'Basis斯科茨代尔',
    country: 'US',
    state: 'AZ',
    city: 'Scottsdale',
    type: 'PUBLIC_US',
    tier: 3,
  },
  {
    name: 'Whitney High School',
    nameZh: '惠特尼高中',
    country: 'US',
    state: 'CA',
    city: 'Cerritos',
    type: 'PUBLIC_US',
    tier: 3,
  },

  // US — Top Private Day Schools
  {
    name: 'Trinity School',
    nameZh: '三一学校',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 5,
    description: 'Top NYC private school',
  },
  {
    name: 'Collegiate School',
    nameZh: '学院学校',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 5,
  },
  {
    name: 'Horace Mann School',
    nameZh: '霍瑞斯曼中学',
    abbreviation: 'Horace Mann',
    country: 'US',
    state: 'NY',
    city: 'Bronx',
    type: 'PRIVATE_US',
    tier: 5,
  },
  {
    name: 'Dalton School',
    nameZh: '道尔顿学校',
    abbreviation: 'Dalton',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 5,
  },
  {
    name: 'Harvard-Westlake School',
    nameZh: '哈佛西湖学校',
    abbreviation: 'HW',
    country: 'US',
    state: 'CA',
    city: 'Los Angeles',
    type: 'PRIVATE_US',
    tier: 5,
    description: 'Top LA private school',
  },
  {
    name: 'The College Preparatory School',
    nameZh: '大学预备学校',
    abbreviation: 'College Prep',
    country: 'US',
    state: 'CA',
    city: 'Oakland',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Lakeside School',
    nameZh: '湖滨学校',
    abbreviation: 'Lakeside',
    country: 'US',
    state: 'WA',
    city: 'Seattle',
    type: 'PRIVATE_US',
    tier: 4,
    description: 'Top Seattle private school (Bill Gates alma mater)',
  },
  {
    name: 'Sidwell Friends School',
    nameZh: '西德威尔友谊中学',
    abbreviation: 'Sidwell',
    country: 'US',
    state: 'DC',
    city: 'Washington',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Brearley School',
    nameZh: '布里尔利学校',
    abbreviation: 'Brearley',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Spence School',
    nameZh: '斯宾塞学校',
    country: 'US',
    state: 'NY',
    city: 'New York',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Roxbury Latin School',
    nameZh: '罗克斯伯里拉丁学校',
    abbreviation: 'Roxbury Latin',
    country: 'US',
    state: 'MA',
    city: 'West Roxbury',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Noble and Greenough School',
    nameZh: '诺贝尔和格里诺学校',
    abbreviation: 'Nobles',
    country: 'US',
    state: 'MA',
    city: 'Dedham',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Winsor School',
    nameZh: '温莎学校',
    country: 'US',
    state: 'MA',
    city: 'Boston',
    type: 'PRIVATE_US',
    tier: 4,
  },
  {
    name: 'Germantown Friends School',
    nameZh: '日耳曼敦友谊学校',
    country: 'US',
    state: 'PA',
    city: 'Philadelphia',
    type: 'PRIVATE_US',
    tier: 3,
  },
  {
    name: 'Menlo School',
    nameZh: '门罗学校',
    country: 'US',
    state: 'CA',
    city: 'Atherton',
    type: 'PRIVATE_US',
    tier: 3,
  },
  {
    name: 'Crystal Springs Uplands School',
    nameZh: '水晶泉高地学校',
    country: 'US',
    state: 'CA',
    city: 'Hillsborough',
    type: 'PRIVATE_US',
    tier: 3,
  },

  // ============================================
  // China — International Schools / Programs (Tier 5)
  // ============================================
  {
    name: 'Shanghai High School International Division',
    nameZh: '上海中学国际部',
    abbreviation: 'SHSID',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 5,
    description: '中国顶级国际学校，Ivy 强 feeder',
  },
  {
    name: 'Shenzhen College of International Education',
    nameZh: '深圳国际交流学院',
    abbreviation: 'SCIE',
    country: 'CN',
    state: '广东',
    city: '深圳',
    type: 'INTL_CN',
    tier: 5,
    description: 'A-Level 体系顶级学校，牛剑/Ivy 录取突出',
  },
  {
    name: 'Beijing National Day School',
    nameZh: '北京十一学校国际部',
    abbreviation: 'BNDS',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 5,
  },
  {
    name: 'The Affiliated High School of Peking University',
    nameZh: '北大附中国际部',
    abbreviation: 'PKUHS',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 5,
  },
  {
    name: 'The High School Affiliated to Renmin University of China',
    nameZh: '人大附中国际部',
    abbreviation: 'RDFZ ICC',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 5,
    description: '北京顶级国际课程中心',
  },
  {
    name: 'UWC Changshu China',
    nameZh: '世界联合学院常熟',
    abbreviation: 'UWC常熟',
    country: 'CN',
    state: '江苏',
    city: '常熟',
    type: 'INTL_CN',
    tier: 5,
    description: 'UWC 体系中国校区',
  },

  // China — International Schools (Tier 4)
  {
    name: 'The Experimental High School Attached to Beijing Normal University',
    nameZh: '北师大实验中学国际部',
    abbreviation: 'BNUEHSID',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Nanjing Foreign Language School',
    nameZh: '南京外国语学校',
    abbreviation: 'NFLS',
    country: 'CN',
    state: '江苏',
    city: '南京',
    type: 'INTL_CN',
    tier: 4,
    description: '南京顶级外语特色学校',
  },
  {
    name: 'Shanghai World Foreign Language Academy',
    nameZh: '上海世界外国语中学',
    abbreviation: 'WFLA',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Shanghai Pinghe Bilingual School',
    nameZh: '上海平和双语学校',
    abbreviation: 'Pinghe',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Dulwich College Shanghai Pudong',
    nameZh: '上海德威英国国际学校浦东校区',
    abbreviation: 'Dulwich SH',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Shanghai American School',
    nameZh: '上海美国学校',
    abbreviation: 'SAS',
    country: 'CN',
    state: '上海',
    city: '上海',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Beijing Shidi High School International Department',
    nameZh: '北京师大附中国际部',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Wuxi Big Bridge Academy',
    nameZh: '无锡大桥实验学校',
    abbreviation: 'Big Bridge',
    country: 'CN',
    state: '江苏',
    city: '无锡',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Suzhou Foreign Language School',
    nameZh: '苏州外国语学校',
    abbreviation: 'SFLS',
    country: 'CN',
    state: '江苏',
    city: '苏州',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: "The High School Affiliated to Xi'an Jiaotong University",
    nameZh: '西安交大附中国际部',
    country: 'CN',
    state: '陕西',
    city: '西安',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: 'Guangzhou Foreign Language School',
    nameZh: '广州外国语学校',
    abbreviation: 'GZFLS',
    country: 'CN',
    state: '广东',
    city: '广州',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: 'Shenzhen Middle School International System',
    nameZh: '深圳中学国际体系',
    abbreviation: 'SZMS Intl',
    country: 'CN',
    state: '广东',
    city: '深圳',
    type: 'INTL_CN',
    tier: 4,
  },
  {
    name: 'Hangzhou Foreign Languages School',
    nameZh: '杭州外国语学校',
    abbreviation: 'HFLS',
    country: 'CN',
    state: '浙江',
    city: '杭州',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: 'Chengdu Shude High School International Department',
    nameZh: '成都树德中学国际部',
    country: 'CN',
    state: '四川',
    city: '成都',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: 'Beijing World Youth Academy',
    nameZh: '北京世青国际学校',
    abbreviation: 'BWYA',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: 'Keystone Academy',
    nameZh: '北京鼎石学校',
    abbreviation: 'Keystone',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 4,
    description: 'IB 体系顶级寄宿学校',
  },
  {
    name: 'Beijing Huijia Private School',
    nameZh: '北京汇佳私立学校',
    abbreviation: 'Huijia',
    country: 'CN',
    state: '北京',
    city: '北京',
    type: 'INTL_CN',
    tier: 3,
  },

  // China — Public Schools (High Overseas Admission) (Tier 3-4)
  {
    name: 'The Affiliated High School of South China Normal University',
    nameZh: '华南师大附中',
    abbreviation: 'SCNUAHS',
    country: 'CN',
    state: '广东',
    city: '广州',
    type: 'PUBLIC_CN',
    tier: 3,
  },
  {
    name: 'Chengdu No.7 High School',
    nameZh: '成都七中',
    country: 'CN',
    state: '四川',
    city: '成都',
    type: 'PUBLIC_CN',
    tier: 3,
  },
  {
    name: 'Wuhan Foreign Languages School',
    nameZh: '武汉外国语学校',
    abbreviation: 'WFLS',
    country: 'CN',
    state: '湖北',
    city: '武汉',
    type: 'INTL_CN',
    tier: 3,
  },
  {
    name: 'Changsha Yali High School International Department',
    nameZh: '长沙雅礼中学国际部',
    country: 'CN',
    state: '湖南',
    city: '长沙',
    type: 'INTL_CN',
    tier: 3,
  },

  // ============================================
  // Singapore
  // ============================================
  {
    name: 'Raffles Institution',
    nameZh: '莱佛士书院',
    abbreviation: 'RI',
    country: 'SG',
    city: 'Singapore',
    type: 'PUBLIC_OTHER',
    tier: 5,
    description: "Singapore's top school, strong Ivy/Oxbridge feeder",
  },
  {
    name: 'Hwa Chong Institution',
    nameZh: '华侨中学',
    abbreviation: 'HCI',
    country: 'SG',
    city: 'Singapore',
    type: 'PUBLIC_OTHER',
    tier: 4,
  },
  {
    name: 'NUS High School of Math and Science',
    nameZh: '新加坡国大数理中学',
    abbreviation: 'NUS High',
    country: 'SG',
    city: 'Singapore',
    type: 'PUBLIC_OTHER',
    tier: 4,
  },
  {
    name: 'Anglo-Chinese School (Independent)',
    nameZh: '英华自主中学',
    abbreviation: 'ACS(I)',
    country: 'SG',
    city: 'Singapore',
    type: 'PRIVATE_OTHER',
    tier: 3,
  },
  {
    name: 'United World College of South East Asia',
    nameZh: 'UWC东南亚',
    abbreviation: 'UWCSEA',
    country: 'SG',
    city: 'Singapore',
    type: 'INTL_OTHER',
    tier: 4,
  },

  // ============================================
  // United Kingdom
  // ============================================
  {
    name: 'Eton College',
    nameZh: '伊顿公学',
    abbreviation: 'Eton',
    country: 'GB',
    state: 'Berkshire',
    city: 'Windsor',
    type: 'PRIVATE_OTHER',
    tier: 5,
    description: 'The most prestigious British public school',
  },
  {
    name: 'Westminster School',
    nameZh: '威斯敏斯特公学',
    abbreviation: 'Westminster UK',
    country: 'GB',
    state: 'London',
    city: 'London',
    type: 'PRIVATE_OTHER',
    tier: 5,
  },
  {
    name: "St Paul's School",
    nameZh: '圣保罗学校',
    abbreviation: "St Paul's UK",
    country: 'GB',
    state: 'London',
    city: 'London',
    type: 'PRIVATE_OTHER',
    tier: 5,
  },
  {
    name: 'Winchester College',
    nameZh: '温切斯特公学',
    abbreviation: 'Winchester',
    country: 'GB',
    state: 'Hampshire',
    city: 'Winchester',
    type: 'PRIVATE_OTHER',
    tier: 5,
  },
  {
    name: 'Harrow School',
    nameZh: '哈罗公学',
    abbreviation: 'Harrow',
    country: 'GB',
    state: 'London',
    city: 'Harrow',
    type: 'PRIVATE_OTHER',
    tier: 4,
  },
  {
    name: 'Rugby School',
    nameZh: '拉格比公学',
    abbreviation: 'Rugby',
    country: 'GB',
    state: 'Warwickshire',
    city: 'Rugby',
    type: 'PRIVATE_OTHER',
    tier: 4,
  },
  {
    name: 'Charterhouse',
    nameZh: '切特豪斯公学',
    country: 'GB',
    state: 'Surrey',
    city: 'Godalming',
    type: 'PRIVATE_OTHER',
    tier: 4,
  },
  {
    name: 'Sevenoaks School',
    nameZh: '七橡树中学',
    abbreviation: 'Sevenoaks',
    country: 'GB',
    state: 'Kent',
    city: 'Sevenoaks',
    type: 'PRIVATE_OTHER',
    tier: 4,
    description: 'Top IB school in the UK',
  },

  // ============================================
  // Canada
  // ============================================
  {
    name: 'Upper Canada College',
    nameZh: '上加拿大学院',
    abbreviation: 'UCC',
    country: 'CA',
    state: 'ON',
    city: 'Toronto',
    type: 'PRIVATE_OTHER',
    tier: 4,
  },
  {
    name: 'Appleby College',
    nameZh: '亚比利学院',
    abbreviation: 'Appleby',
    country: 'CA',
    state: 'ON',
    city: 'Oakville',
    type: 'PRIVATE_OTHER',
    tier: 4,
  },
  {
    name: 'Crescent School',
    nameZh: '新月学校',
    country: 'CA',
    state: 'ON',
    city: 'Toronto',
    type: 'PRIVATE_OTHER',
    tier: 3,
  },
  {
    name: 'Havergal College',
    nameZh: '海福格尔学院',
    country: 'CA',
    state: 'ON',
    city: 'Toronto',
    type: 'PRIVATE_OTHER',
    tier: 3,
  },
  {
    name: "St. Andrew's College",
    nameZh: '圣安德鲁学院',
    country: 'CA',
    state: 'ON',
    city: 'Aurora',
    type: 'PRIVATE_OTHER',
    tier: 3,
  },

  // ============================================
  // Other Countries
  // ============================================
  {
    name: 'Seoul International School',
    nameZh: '首尔国际学校',
    abbreviation: 'SIS',
    country: 'KR',
    city: 'Seoul',
    type: 'INTL_OTHER',
    tier: 3,
  },
  {
    name: 'Korea International School',
    nameZh: '韩国国际学校',
    abbreviation: 'KIS',
    country: 'KR',
    city: 'Seoul',
    type: 'INTL_OTHER',
    tier: 3,
  },
  {
    name: 'International School Bangkok',
    nameZh: '曼谷国际学校',
    abbreviation: 'ISB',
    country: 'TH',
    city: 'Bangkok',
    type: 'INTL_OTHER',
    tier: 3,
  },
  {
    name: 'Hong Kong International School',
    nameZh: '香港国际学校',
    abbreviation: 'HKIS',
    country: 'HK',
    city: 'Hong Kong',
    type: 'INTL_OTHER',
    tier: 4,
  },
  {
    name: 'Chinese International School',
    nameZh: '汉基国际学校',
    abbreviation: 'CIS',
    country: 'HK',
    city: 'Hong Kong',
    type: 'INTL_OTHER',
    tier: 4,
  },
  {
    name: 'Li Po Chun United World College',
    nameZh: '李宝椿联合世界书院',
    abbreviation: 'LPC UWC',
    country: 'HK',
    city: 'Hong Kong',
    type: 'INTL_OTHER',
    tier: 4,
  },
  {
    name: 'UWC Atlantic College',
    nameZh: 'UWC大西洋学院',
    abbreviation: 'UWC Atlantic',
    country: 'GB',
    state: 'Wales',
    city: 'Llantwit Major',
    type: 'INTL_OTHER',
    tier: 5,
    description: 'The original UWC campus',
  },
  {
    name: 'UWC Pearson College',
    nameZh: 'UWC皮尔逊学院',
    abbreviation: 'UWC Pearson',
    country: 'CA',
    state: 'BC',
    city: 'Victoria',
    type: 'INTL_OTHER',
    tier: 4,
  },
  {
    name: 'UWC Robert Bosch College',
    nameZh: 'UWC罗伯特·博世学院',
    abbreviation: 'UWC RBC',
    country: 'DE',
    city: 'Freiburg',
    type: 'INTL_OTHER',
    tier: 4,
  },

  // ============================================
  // India
  // ============================================
  {
    name: 'Doon School',
    nameZh: '杜恩学校',
    abbreviation: 'Doon',
    country: 'IN',
    state: 'Uttarakhand',
    city: 'Dehradun',
    type: 'PRIVATE_OTHER',
    tier: 4,
  },
  {
    name: 'Woodstock School',
    nameZh: '伍德斯托克学校',
    country: 'IN',
    state: 'Uttarakhand',
    city: 'Mussoorie',
    type: 'INTL_OTHER',
    tier: 3,
  },
  {
    name: 'Mahindra UWC India',
    nameZh: 'UWC印度马恒达学院',
    abbreviation: 'UWC India',
    country: 'IN',
    state: 'Maharashtra',
    city: 'Pune',
    type: 'INTL_OTHER',
    tier: 4,
  },

  // ============================================
  // Japan
  // ============================================
  {
    name: 'ISAK Japan',
    nameZh: 'ISAK日本国际学校',
    abbreviation: 'UWC ISAK',
    country: 'JP',
    state: 'Nagano',
    city: 'Karuizawa',
    type: 'INTL_OTHER',
    tier: 4,
    description: 'UWC member school in Japan',
  },
];

async function seedHighSchools() {
  console.log('🏫 Seeding high school reference data...');

  let created = 0;
  let updated = 0;

  for (const hs of highSchools) {
    const existing = hs.abbreviation
      ? await prisma.highSchool.findUnique({
          where: { abbreviation: hs.abbreviation },
        })
      : await prisma.highSchool.findUnique({
          where: {
            name_country_state: {
              name: hs.name,
              country: hs.country,
              state: hs.state || '',
            },
          },
        });

    if (existing) {
      await prisma.highSchool.update({
        where: { id: existing.id },
        data: {
          name: hs.name,
          nameZh: hs.nameZh,
          abbreviation: hs.abbreviation,
          country: hs.country,
          state: hs.state,
          city: hs.city,
          type: hs.type,
          tier: hs.tier,
          description: hs.description,
        },
      });
      updated++;
    } else {
      await prisma.highSchool.create({ data: hs });
      created++;
    }
  }

  console.log(
    `✅ High schools seeded: ${created} created, ${updated} updated (total: ${highSchools.length})`,
  );
}

// Direct execution
seedHighSchools()
  .catch((e) => {
    console.error('❌ High school seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());

export { seedHighSchools, highSchools };
