/**
 * Unified school name alias mapping.
 *
 * Single source of truth for converting common abbreviations and informal names
 * to official school names. Used by:
 * - import-normalizers.ts (API batch import)
 * - import-cases-csv.ts (CLI import script)
 * - scrape-reddit-cases.ts (Reddit scraper)
 *
 * All keys are stored in lowercase for case-insensitive lookup.
 */

export const SCHOOL_ALIASES: Record<string, string> = {
  // === Top 20 ===
  mit: 'Massachusetts Institute of Technology',
  harvard: 'Harvard University',
  stanford: 'Stanford University',
  yale: 'Yale University',
  princeton: 'Princeton University',
  columbia: 'Columbia University',
  upenn: 'University of Pennsylvania',
  penn: 'University of Pennsylvania',
  brown: 'Brown University',
  dartmouth: 'Dartmouth College',
  cornell: 'Cornell University',
  duke: 'Duke University',
  northwestern: 'Northwestern University',
  caltech: 'California Institute of Technology',
  jhu: 'Johns Hopkins University',
  'johns hopkins': 'Johns Hopkins University',
  uchicago: 'University of Chicago',
  chicago: 'University of Chicago',
  rice: 'Rice University',
  vanderbilt: 'Vanderbilt University',
  'notre dame': 'University of Notre Dame',
  washu: 'Washington University in St. Louis',
  wustl: 'Washington University in St. Louis',
  emory: 'Emory University',
  georgetown: 'Georgetown University',

  // === UC System ===
  ucla: 'University of California, Los Angeles',
  berkeley: 'University of California, Berkeley',
  ucb: 'University of California, Berkeley',
  cal: 'University of California, Berkeley',
  ucsd: 'University of California, San Diego',
  uci: 'University of California, Irvine',
  ucsb: 'University of California, Santa Barbara',
  ucd: 'University of California, Davis',
  'uc davis': 'University of California, Davis',
  ucr: 'University of California, Riverside',
  ucsc: 'University of California, Santa Cruz',
  'uc santa cruz': 'University of California, Santa Cruz',
  'uc merced': 'University of California, Merced',
  usc: 'University of Southern California',

  // === Other Top Schools ===
  cmu: 'Carnegie Mellon University',
  'carnegie mellon': 'Carnegie Mellon University',
  nyu: 'New York University',
  umich: 'University of Michigan, Ann Arbor',
  michigan: 'University of Michigan, Ann Arbor',
  uva: 'University of Virginia',
  virginia: 'University of Virginia',
  unc: 'University of North Carolina at Chapel Hill',
  'chapel hill': 'University of North Carolina at Chapel Hill',
  'georgia tech': 'Georgia Institute of Technology',
  gt: 'Georgia Institute of Technology',
  gatech: 'Georgia Institute of Technology',
  'ut austin': 'University of Texas at Austin',
  utaustin: 'University of Texas at Austin',
  texas: 'University of Texas at Austin',
  uiuc: 'University of Illinois Urbana-Champaign',
  illinois: 'University of Illinois Urbana-Champaign',
  uw: 'University of Washington',
  udub: 'University of Washington',
  purdue: 'Purdue University',
  osu: 'Ohio State University',
  'ohio state': 'Ohio State University',
  'penn state': 'Penn State University',
  psu: 'Penn State University',
  pennstate: 'Penn State University',
  bu: 'Boston University',
  bc: 'Boston College',
  tufts: 'Tufts University',
  neu: 'Northeastern University',
  northeastern: 'Northeastern University',
  uf: 'University of Florida',
  florida: 'University of Florida',
  uga: 'University of Georgia',

  // === 51–100 Ranked Schools ===
  rochester: 'University of Rochester',
  case: 'Case Western Reserve University',
  'case western': 'Case Western Reserve University',
  cwru: 'Case Western Reserve University',
  tulane: 'Tulane University',
  umn: 'University of Minnesota, Twin Cities',
  minnesota: 'University of Minnesota, Twin Cities',
  uconn: 'University of Connecticut',
  'virginia tech': 'Virginia Tech',
  vt: 'Virginia Tech',
  vatech: 'Virginia Tech',
  pepperdine: 'Pepperdine University',
  gwu: 'George Washington University',
  gw: 'George Washington University',
  scu: 'Santa Clara University',
  'santa clara': 'Santa Clara University',
  syracuse: 'Syracuse University',
  cuse: 'Syracuse University',
  pitt: 'University of Pittsburgh',
  pittsburgh: 'University of Pittsburgh',
  miami: 'University of Miami',
  rpi: 'Rensselaer Polytechnic Institute',
  rensselaer: 'Rensselaer Polytechnic Institute',
  stevens: 'Stevens Institute of Technology',
  iu: 'Indiana University Bloomington',
  indiana: 'Indiana University Bloomington',
  msu: 'Michigan State University',
  'michigan state': 'Michigan State University',
  iowa: 'University of Iowa',
  udelaware: 'University of Delaware',
  delaware: 'University of Delaware',
  'cu boulder': 'University of Colorado Boulder',
  boulder: 'University of Colorado Boulder',
  baylor: 'Baylor University',
  clemson: 'Clemson University',
  fordham: 'Fordham University',
  'stony brook': 'Stony Brook University',
  sbu: 'Stony Brook University',
  au: 'American University',
  american: 'American University',
  marquette: 'Marquette University',
  ub: 'University at Buffalo',
  buffalo: 'University at Buffalo',
  'nc state': 'North Carolina State University',
  ncsu: 'North Carolina State University',
  umass: 'University of Massachusetts Amherst',
  'umass amherst': 'University of Massachusetts Amherst',
  drexel: 'Drexel University',
  temple: 'Temple University',
  wpi: 'Worcester Polytechnic Institute',
  arizona: 'University of Arizona',
  uarizona: 'University of Arizona',
  howard: 'Howard University',
  rit: 'Rochester Institute of Technology',
  iit: 'Illinois Institute of Technology',
  brandeis: 'Brandeis University',
  smu: 'Southern Methodist University',
  denver: 'University of Denver',
  mines: 'Colorado School of Mines',
  usd: 'University of San Diego',
  gonzaga: 'Gonzaga University',
  villanova: 'Villanova University',
  nova: 'Villanova University',
  rutgers: 'Rutgers University-New Brunswick',
  umd: 'University of Maryland, College Park',
  maryland: 'University of Maryland, College Park',
  lehigh: 'Lehigh University',
  tamu: 'Texas A&M University',
  'texas a&m': 'Texas A&M University',
  'wake forest': 'Wake Forest University',
  wake: 'Wake Forest University',
  wisconsin: 'University of Wisconsin-Madison',
  'uw madison': 'University of Wisconsin-Madison',
  uwisc: 'University of Wisconsin-Madison',
  lmu: 'Loyola Marymount University',
  slu: 'Saint Louis University',

  // === 101–150 Ranked Schools ===
  auburn: 'Auburn University',
  'south carolina': 'University of South Carolina',
  utah: 'University of Utah',
  depaul: 'DePaul University',
  'seton hall': 'Seton Hall University',
  oregon: 'University of Oregon',
  uo: 'University of Oregon',
  usf: 'University of San Francisco',
  clarkson: 'Clarkson University',
  kentucky: 'University of Kentucky',
  uk: 'University of Kentucky',
  kansas: 'University of Kansas',
  ku: 'University of Kansas',
  sdsu: 'San Diego State University',
  'san diego state': 'San Diego State University',
  'new school': 'The New School',
  parsons: 'The New School',
  alabama: 'University of Alabama',
  bama: 'University of Alabama',
  oklahoma: 'University of Oklahoma',
  ou: 'University of Oklahoma',
  asu: 'Arizona State University',
  'arizona state': 'Arizona State University',
  mizzou: 'University of Missouri',
  missouri: 'University of Missouri',
  'loyola chicago': 'Loyola University Chicago',
  'iowa state': 'Iowa State University',
  isu: 'Iowa State University',
  tennessee: 'University of Tennessee',
  utk: 'University of Tennessee',
  nebraska: 'University of Nebraska-Lincoln',
  unl: 'University of Nebraska-Lincoln',
  'oregon state': 'Oregon State University',
  'osu oregon': 'Oregon State University',
  'new hampshire': 'University of New Hampshire',
  unh: 'University of New Hampshire',
  cincinnati: 'University of Cincinnati',
  'uc cincinnati': 'University of Cincinnati',
  'colorado state': 'Colorado State University',
  csu: 'Colorado State University',
  vermont: 'University of Vermont',
  uvm: 'University of Vermont',
  gmu: 'George Mason University',
  'george mason': 'George Mason University',
  lsu: 'Louisiana State University',
  'louisiana state': 'Louisiana State University',
  houston: 'University of Houston',
  uh: 'University of Houston',
  arkansas: 'University of Arkansas',
  uark: 'University of Arkansas',
  hawaii: 'University of Hawaii at Manoa',
  'uh manoa': 'University of Hawaii at Manoa',
  fsu: 'Florida State University',
  'florida state': 'Florida State University',
  'rhode island': 'University of Rhode Island',
  uri: 'University of Rhode Island',
  'k-state': 'Kansas State University',
  'kansas state': 'Kansas State University',
  'missouri s&t': 'Missouri University of Science and Technology',
  rolla: 'Missouri University of Science and Technology',
  wsu: 'Washington State University',
  wazzu: 'Washington State University',
  'washington state': 'Washington State University',

  // === 151–200+ Ranked Schools ===
  maine: 'University of Maine',
  ucf: 'University of Central Florida',
  'central florida': 'University of Central Florida',
  'illinois state': 'Illinois State University',
  hofstra: 'Hofstra University',
  rowan: 'Rowan University',
  adelphi: 'Adelphi University',
  binghamton: 'SUNY Binghamton University',
  'suny binghamton': 'SUNY Binghamton University',
  'mississippi state': 'Mississippi State University',
  'ohio u': 'Ohio University',
  'kent state': 'Kent State University',
  'new mexico': 'University of New Mexico',
  unm: 'University of New Mexico',
  'ball state': 'Ball State University',
  wyoming: 'University of Wyoming',
  'west virginia': 'West Virginia University',
  wvu: 'West Virginia University',
  'north dakota': 'University of North Dakota',
  'south dakota': 'University of South Dakota',
  'montana state': 'Montana State University',
  unr: 'University of Nevada, Reno',
  reno: 'University of Nevada, Reno',
  'portland state': 'Portland State University',
  'texas tech': 'Texas Tech University',
  ttu: 'Texas Tech University',
  idaho: 'University of Idaho',
  'north texas': 'University of North Texas',
  unt: 'University of North Texas',
  unlv: 'University of Nevada, Las Vegas',
  'las vegas': 'University of Nevada, Las Vegas',
  sjsu: 'San Jose State University',
  'san jose state': 'San Jose State University',
  'bowling green': 'Bowling Green State University',
  bgsu: 'Bowling Green State University',
  csuf: 'California State University, Fullerton',
  'cal state fullerton': 'California State University, Fullerton',
  csulb: 'California State University, Long Beach',
  'long beach state': 'California State University, Long Beach',
  'cal poly': 'California Polytechnic State University, San Luis Obispo',
  'cal poly slo': 'California Polytechnic State University, San Luis Obispo',
  ndsu: 'North Dakota State University',
  'sdsu state': 'South Dakota State University',
  akron: 'University of Akron',
  toledo: 'University of Toledo',
  'wayne state': 'Wayne State University',
  'umass lowell': 'University of Massachusetts Lowell',
  'oklahoma state': 'Oklahoma State University',
  okstate: 'Oklahoma State University',
  nmsu: 'New Mexico State University',
  csun: 'California State University, Northridge',
  'southern miss': 'University of Southern Mississippi',
  niu: 'Northern Illinois University',
  emu: 'Eastern Michigan University',
  uwm: 'University of Wisconsin-Milwaukee',
  'western michigan': 'Western Michigan University',
  'idaho state': 'Idaho State University',
  uta: 'University of Texas at Arlington',
  'ut arlington': 'University of Texas at Arlington',
  memphis: 'University of Memphis',
  utsa: 'University of Texas at San Antonio',
  'ut san antonio': 'University of Texas at San Antonio',
  'cleveland state': 'Cleveland State University',
  fiu: 'Florida International University',
  'georgia state': 'Georgia State University',
  gsu: 'Georgia State University',
  'umass boston': 'University of Massachusetts Boston',
  odu: 'Old Dominion University',
  'old dominion': 'Old Dominion University',
  'wright state': 'Wright State University',
  cmich: 'Central Michigan University',
  'central michigan': 'Central Michigan University',
  iupui: 'Indiana University-Purdue University Indianapolis',
  'wichita state': 'Wichita State University',

  // === Liberal Arts Colleges ===
  williams: 'Williams College',
  amherst: 'Amherst College',
  swarthmore: 'Swarthmore College',
  pomona: 'Pomona College',
  wellesley: 'Wellesley College',
  bowdoin: 'Bowdoin College',
  middlebury: 'Middlebury College',
  carleton: 'Carleton College',
  cmc: 'Claremont McKenna College',
  'claremont mckenna': 'Claremont McKenna College',
  hamilton: 'Hamilton College',
  haverford: 'Haverford College',
  vassar: 'Vassar College',
  grinnell: 'Grinnell College',
  colgate: 'Colgate University',
  davidson: 'Davidson College',
  smith: 'Smith College',
  'w&l': 'Washington and Lee University',
  'washington and lee': 'Washington and Lee University',
  colby: 'Colby College',
  bates: 'Bates College',
  barnard: 'Barnard College',

  // === Art Schools ===
  risd: 'Rhode Island School of Design',
  pratt: 'Pratt Institute',
  saic: 'School of the Art Institute of Chicago',
  calarts: 'California Institute of the Arts',
  artcenter: 'ArtCenter College of Design',
  scad: 'Savannah College of Art and Design',
  mica: 'Maryland Institute College of Art',
  cca: 'California College of the Arts',

  // === Music Schools ===
  juilliard: 'The Juilliard School',
  berklee: 'Berklee College of Music',
  curtis: 'Curtis Institute of Music',
  nec: 'New England Conservatory',
  msm: 'Manhattan School of Music',

  // === Engineering Schools ===
  'harvey mudd': 'Harvey Mudd College',
  hmc: 'Harvey Mudd College',
  'rose-hulman': 'Rose-Hulman Institute of Technology',
  'rose hulman': 'Rose-Hulman Institute of Technology',
  cooper: 'Cooper Union',
  'cooper union': 'Cooper Union',
  olin: 'Olin College of Engineering',

  // === Additional Schools ===
  'app state': 'Appalachian State University',
  jmu: 'James Madison University',
  uncw: 'University of North Carolina Wilmington',
  gvsu: 'Grand Valley State University',
  towson: 'Towson University',
  'sac state': 'California State University, Sacramento',
  utd: 'University of Texas at Dallas',
  'ut dallas': 'University of Texas at Dallas',
  'usf tampa': 'University of South Florida',
};

/**
 * Resolve a school name alias to its official name.
 * Returns the original (trimmed) name if no alias is found.
 */
export function resolveSchoolAlias(name: string): string {
  const lower = name.toLowerCase().trim();
  return SCHOOL_ALIASES[lower] ?? name.trim();
}

/**
 * Fuzzy match a school name against the alias map.
 * Used by the Reddit scraper for more flexible matching.
 * Returns null if no match found.
 */
export function findSchoolByAlias(rawName: string): string | null {
  const normalized = rawName.toLowerCase().trim();

  // Direct match
  if (SCHOOL_ALIASES[normalized]) {
    return SCHOOL_ALIASES[normalized];
  }

  // Check if input contains any alias
  for (const [alias, fullName] of Object.entries(SCHOOL_ALIASES)) {
    if (normalized === alias || normalized.includes(alias)) {
      return fullName;
    }
  }

  // Check if any alias contains the input (only for inputs > 3 chars to avoid false matches)
  if (normalized.length > 3) {
    for (const [alias, fullName] of Object.entries(SCHOOL_ALIASES)) {
      if (alias.includes(normalized)) {
        return fullName;
      }
    }
  }

  return null;
}
