name: Feature Request
description: Propose a new feature or improvement
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Describe the feature you would like to see added.

  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module does this affect?
      options:
        - Web Frontend
        - API Backend
        - Mobile App
        - AI Agent
        - Database/Prisma
        - Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - 'High: Blocking or critical for upcoming release'
        - 'Medium: Important but not urgent'
        - 'Low: Nice to have'
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, references, or any other context
