import { borderRadius, fontFamily, fontSize, fontWeight, spacing } from '@/utils/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  editorContent: {},
  editorContentKeyboard: { paddingBottom: 120 },
  dimmedTool: { opacity: 0.5 },
  container: { flex: 1 },
  header: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderBottomWidth: 1 },
  titleInput: { fontSize: fontSize.xl, fontWeight: fontWeight.bold, marginBottom: spacing.xs },
  headerMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  wordCountText: { fontSize: fontSize.sm },
  wordCountNum: { fontFamily: fontFamily.mono },
  saveText: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
  editorScroll: { flex: 1 },
  contentInput: {
    flex: 1,
    padding: spacing.lg,
    fontSize: fontSize.base,
    lineHeight: 26,
    minHeight: 300,
  },
  aiToolbar: { borderTopWidth: 1, paddingTop: spacing.sm },
  aiLoadingBar: { paddingHorizontal: spacing.lg, paddingBottom: spacing.xs },
  aiLoadingText: { fontSize: fontSize.xs, fontWeight: fontWeight.medium },
  toolsRow: { paddingHorizontal: spacing.lg, gap: spacing.sm },
  toolButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
  },
  toolLabel: { fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  resultContainer: { maxHeight: 500, paddingHorizontal: spacing.lg },
  scoreCard: {
    alignItems: 'center',
    padding: spacing['2xl'],
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    marginBottom: spacing.lg,
  },
  scoreValue: { fontSize: 48, fontWeight: fontWeight.bold, fontFamily: fontFamily.mono },
  scoreLabel: { fontSize: fontSize.sm, marginTop: spacing.xs },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
  },
  categoryInfo: { flex: 1, marginRight: spacing.md },
  categoryName: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing.xs,
  },
  categoryFeedback: { fontSize: fontSize.sm },
  summarySection: { marginTop: spacing.lg },
  summaryTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing.sm,
  },
  summaryText: { fontSize: fontSize.sm, lineHeight: 22 },
  suggestionsSection: { marginTop: spacing.lg },
  suggestionsTitle: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing.sm,
  },
  suggestionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.sm,
    alignItems: 'flex-start',
  },
  suggestionText: { flex: 1, fontSize: fontSize.sm, lineHeight: 20 },
  changeCard: {
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    marginBottom: spacing.md,
  },
  changeOriginal: {
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    fontSize: fontSize.sm,
    overflow: 'hidden',
  },
  changeArrow: { alignSelf: 'center', marginVertical: spacing.xs },
  changeRevised: {
    padding: spacing.sm,
    borderRadius: borderRadius.sm,
    fontSize: fontSize.sm,
    overflow: 'hidden',
  },
  changeReason: { fontSize: fontSize.xs, marginTop: spacing.sm, fontStyle: 'italic' },
  resultActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
  },
  resultActionBtn: { flex: 1 },
  ideaCard: {
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    marginBottom: spacing.md,
  },
  ideaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  ideaTitle: { fontSize: fontSize.base, fontWeight: fontWeight.semibold },
  ideaDesc: { fontSize: fontSize.sm, lineHeight: 20 },
  tapToCopy: { fontSize: fontSize.xs, marginTop: spacing.sm },
  continuationText: {
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    fontSize: fontSize.base,
    lineHeight: 26,
  },
  rewriteInput: { paddingHorizontal: spacing.lg },
  rewriteLabel: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing.sm,
  },
  rewriteTextInput: {
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    fontSize: fontSize.base,
    minHeight: 80,
    marginBottom: spacing.md,
  },
  rewriteButton: { marginBottom: spacing.lg },
  openingCard: {
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    marginBottom: spacing.md,
  },
  openingText: { fontSize: fontSize.sm, lineHeight: 22, marginVertical: spacing.sm },
  openingActions: { flexDirection: 'row', gap: spacing.sm },
  smallAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.md,
  },
  smallActionText: { fontSize: fontSize.sm },
});
