export const TEST_TYPES = [
  'SAT',
  'ACT',
  'TOEFL',
  'IELTS',
  'DUOLINGO',
  'AP',
  'IB',
  'A_LEVEL',
  'IGCSE',
];

export const SUBJECT_MAP: Record<string, string[]> = {
  AP: [
    'Calculus AB',
    'Calculus BC',
    'Statistics',
    'Physics C: Mechanics',
    'Physics C: E&M',
    'Physics 1',
    'Physics 2',
    'Chemistry',
    'Biology',
    'Computer Science A',
    'CS Principles',
    'English Language',
    'English Literature',
    'US History',
    'World History',
    'European History',
    'Psychology',
    'Macroeconomics',
    'Microeconomics',
    'Environmental Science',
    'Chinese Language',
    'Spanish Language',
  ],
  IB: [
    'English A',
    'Chinese A',
    'English B',
    'Chinese B',
    'Spanish B',
    'French B',
    'History',
    'Economics',
    'Psychology',
    'Geography',
    'Business Management',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Science',
    'ESS',
    'Mathematics AA',
    'Mathematics AI',
    'Visual Arts',
    'Music',
  ],
  A_LEVEL: [
    'Mathematics',
    'Further Mathematics',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Science',
    'Economics',
    'Business',
    'Accounting',
    'History',
    'Geography',
    'Psychology',
    'Sociology',
    'English Literature',
    'Chinese',
    'French',
    'Spanish',
    'Art & Design',
  ],
  IGCSE: [
    'Mathematics',
    'Additional Math',
    'English Language',
    'English Literature',
    'Physics',
    'Chemistry',
    'Biology',
    'Combined Science',
    'Chinese (First Language)',
    'Chinese (Second Language)',
    'French',
    'Spanish',
    'History',
    'Geography',
    'Economics',
    'Business Studies',
    'Computer Science',
    'Accounting',
    'Art & Design',
    'Music',
  ],
};

export const NEEDS_SUBJECT = ['AP', 'IB', 'A_LEVEL', 'IGCSE'];
export const NEEDS_SUBSCORES: Record<string, string[]> = {
  SAT: ['readingEBRW', 'math'],
  TOEFL: ['reading', 'listening', 'speaking', 'writing'],
};
