export type ClientSurfaceState = 'navigable' | 'deep-link-only' | 'hidden' | 'retired';

export interface ClientClosureSurface {
  platform: 'web' | 'mobile';
  route: string;
  state: ClientSurfaceState;
  entries: string[];
  operations: Array<{ method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'; path: string }>;
  contractTest: string;
}

export const CLIENT_CLOSURE_MANIFEST: ClientClosureSurface[] = [
  {
    platform: 'web',
    route: '/prediction',
    state: 'navigable',
    entries: ['apps/web/src/components/layout/header.tsx'],
    operations: [
      { method: 'POST', path: '/predictions' },
      { method: 'GET', path: '/predictions/dashboard' },
      { method: 'GET', path: '/predictions/history' },
      { method: 'PATCH', path: '/predictions/:schoolId/result' },
    ],
    contractTest: 'apps/api/test/prediction-closure.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/prediction',
    state: 'navigable',
    entries: ['apps/mobile/src/components/features/home/QuickActionsGrid.tsx'],
    operations: [
      { method: 'POST', path: '/predictions' },
      { method: 'GET', path: '/predictions/dashboard' },
      { method: 'PATCH', path: '/predictions/:schoolId/result' },
    ],
    contractTest: 'apps/api/test/prediction-closure.e2e-spec.ts',
  },
  {
    platform: 'web',
    route: '/outcomes',
    state: 'navigable',
    entries: ['apps/web/src/app/[locale]/(main)/prediction/page.tsx'],
    operations: [
      { method: 'POST', path: '/predictions/outcomes' },
      { method: 'GET', path: '/predictions/outcomes/me' },
      { method: 'GET', path: '/predictions/outcomes/me/stats' },
      { method: 'GET', path: '/predictions/outcomes/pending-decisions' },
      { method: 'POST', path: '/predictions/outcomes/:id/evidence' },
    ],
    contractTest: 'apps/api/test/outcome-closure.e2e-spec.ts',
  },
  {
    platform: 'web',
    route: '/schools/compare',
    state: 'navigable',
    entries: ['apps/web/src/app/[locale]/(main)/schools/_components/SchoolToolbar.tsx'],
    operations: [{ method: 'GET', path: '/schools/:id' }],
    contractTest: 'e2e/feature-closure.spec.ts',
  },
  {
    platform: 'web',
    route: '/schools',
    state: 'navigable',
    entries: ['apps/web/src/components/layout/header.tsx'],
    operations: [
      { method: 'GET', path: '/recommendations/preflight' },
      { method: 'POST', path: '/recommendations' },
      { method: 'GET', path: '/recommendations/history' },
      { method: 'GET', path: '/recommendations/:id' },
      { method: 'DELETE', path: '/recommendations/:id' },
    ],
    contractTest: 'apps/api/test/ai-features-closure.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/recommendation',
    state: 'navigable',
    entries: ['apps/mobile/src/app/(tabs)/more.tsx'],
    operations: [
      { method: 'GET', path: '/recommendations/preflight' },
      { method: 'POST', path: '/recommendations' },
      { method: 'GET', path: '/recommendations/history' },
      { method: 'GET', path: '/recommendations/:id' },
      { method: 'DELETE', path: '/recommendations/:id' },
    ],
    contractTest: 'apps/api/test/ai-features-closure.e2e-spec.ts',
  },
  {
    platform: 'web',
    route: '/points',
    state: 'retired',
    entries: [],
    operations: [],
    contractTest: 'scripts/check-client-closure.ts',
  },
  {
    platform: 'web',
    route: '/admin/points',
    state: 'retired',
    entries: [],
    operations: [],
    contractTest: 'scripts/check-client-closure.ts',
  },
  {
    platform: 'mobile',
    route: '/points',
    state: 'retired',
    entries: [],
    operations: [],
    contractTest: 'scripts/check-client-closure.ts',
  },
  {
    platform: 'mobile',
    route: '/verification',
    state: 'navigable',
    entries: ['apps/mobile/src/app/(tabs)/more.tsx'],
    operations: [
      { method: 'GET', path: '/verifications/status' },
      { method: 'GET', path: '/verifications/my' },
      { method: 'GET', path: '/cases/me' },
      { method: 'POST', path: '/verifications' },
    ],
    contractTest: 'apps/api/test/verification.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/vault',
    state: 'navigable',
    entries: ['apps/mobile/src/app/(tabs)/more.tsx'],
    operations: [
      { method: 'GET', path: '/vaults' },
      { method: 'GET', path: '/vaults/stats' },
      { method: 'GET', path: '/vaults/generate-password' },
      { method: 'GET', path: '/vaults/:id' },
      { method: 'POST', path: '/vaults' },
      { method: 'PUT', path: '/vaults/:id' },
      { method: 'DELETE', path: '/vaults/:id' },
    ],
    contractTest: 'apps/api/test/vault.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/timeline',
    state: 'navigable',
    entries: ['apps/mobile/src/app/(tabs)/more.tsx'],
    operations: [
      { method: 'GET', path: '/timelines' },
      { method: 'GET', path: '/timelines/:id' },
      { method: 'POST', path: '/timelines/tasks' },
    ],
    contractTest: 'apps/api/test/timeline.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/security',
    state: 'navigable',
    entries: ['apps/mobile/src/screens/settings/SettingsScreen.tsx'],
    operations: [{ method: 'POST', path: '/auth/logout' }],
    contractTest: 'apps/api/test/auth-sessions.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/resume',
    state: 'navigable',
    entries: ['apps/mobile/src/app/(tabs)/more.tsx'],
    operations: [
      { method: 'GET', path: '/resumes' },
      { method: 'POST', path: '/resumes' },
      { method: 'GET', path: '/resumes/:id' },
      { method: 'PUT', path: '/resumes/:id' },
      { method: 'DELETE', path: '/resumes/:id' },
      { method: 'POST', path: '/resumes/:id/duplicate' },
      { method: 'POST', path: '/resumes/:id/import-profile' },
      { method: 'PUT', path: '/resumes/:id/sections/:id' },
      { method: 'PUT', path: '/resumes/:id/sections/reorder' },
    ],
    contractTest: 'apps/api/test/resume.e2e-spec.ts',
  },
  {
    platform: 'mobile',
    route: '/peer-review',
    state: 'retired',
    entries: [],
    operations: [],
    contractTest: 'scripts/check-client-closure.ts',
  },
  {
    platform: 'web',
    route: '/settings/subscription',
    state: 'retired',
    entries: [],
    operations: [],
    contractTest: 'scripts/check-client-closure.ts',
  },
  {
    platform: 'mobile',
    route: '/subscription',
    state: 'retired',
    entries: [],
    operations: [],
    contractTest: 'scripts/check-client-closure.ts',
  },
  {
    platform: 'web',
    route: '/admin/payments',
    state: 'navigable',
    entries: ['apps/web/src/app/[locale]/(main)/admin/_components/admin-sidebar.tsx'],
    operations: [
      { method: 'GET', path: '/admin/payments' },
      { method: 'GET', path: '/admin/payments/stats' },
    ],
    contractTest: 'apps/api/src/modules/subscription/payment-admin.controller.spec.ts',
  },
];
