/**
 * Auto-generate docs/REPO_SNAPSHOT.md with accurate repo statistics.
 * Usage: npx tsx scripts/generate-repo-snapshot.ts | pnpm snapshot
 */

import * as fs from 'fs';
import * as path from 'path';

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.resolve(ROOT, 'docs/REPO_SNAPSHOT.md');
const SCHEMA = path.resolve(ROOT, 'apps/api/prisma/schema.prisma');

// ── Helpers ─────────────────────────────────────────────────

function getDirs(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);
}

function countFiles(
  dir: string,
  extensions: string[],
  recursive = false,
  opts: { includeTests?: boolean } = {}
): number {
  if (!fs.existsSync(dir)) return 0;
  if (!recursive) {
    return fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((d) => d.isFile() && extensions.some((ext) => d.name.endsWith(ext))).length;
  }
  const excludeDirs = opts.includeTests
    ? ['node_modules', 'dist', '.next']
    : ['node_modules', 'dist', '.next', '__tests__', '__mocks__'];
  let count = 0;
  const walk = (d: string) => {
    const entries = fs.readdirSync(d, { withFileTypes: true });
    for (const entry of entries) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) {
        if (excludeDirs.includes(entry.name)) continue;
        walk(full);
      } else if (extensions.some((ext) => entry.name.endsWith(ext))) {
        count++;
      }
    }
  };
  walk(dir);
  return count;
}

function countPattern(filePath: string, pattern: RegExp): number {
  if (!fs.existsSync(filePath)) return 0;
  const content = fs.readFileSync(filePath, 'utf8');
  return (content.match(pattern) || []).length;
}

function lineCount(filePath: string): number {
  if (!fs.existsSync(filePath)) return 0;
  return fs.readFileSync(filePath, 'utf8').split('\n').length;
}

// ── Counters ────────────────────────────────────────────────

function gather() {
  const backendModules = getDirs(path.resolve(ROOT, 'apps/api/src/modules')).length;
  const prismaModels = countPattern(SCHEMA, /^model\s+\w+\s*\{/gm);
  const prismaEnums = countPattern(SCHEMA, /^enum\s+\w+\s*\{/gm);
  const schemaLines = lineCount(SCHEMA);

  const frontendRoutes = getDirs(path.resolve(ROOT, 'apps/web/src/app/[locale]/(main)')).length;
  const frontendFeatures = getDirs(path.resolve(ROOT, 'apps/web/src/components/features')).length;
  const uiComponents = countFiles(path.resolve(ROOT, 'apps/web/src/components/ui'), ['.tsx']);
  const mobileScreens = countFiles(path.resolve(ROOT, 'apps/mobile/src/app'), ['.tsx'], true);
  const mobileComponents = countFiles(
    path.resolve(ROOT, 'apps/mobile/src/components'),
    ['.tsx'],
    true
  );
  const sharedTypes = countFiles(path.resolve(ROOT, 'packages/shared/src/types'), ['.ts']);

  const agents = countFiles(path.resolve(ROOT, '.claude/agents'), ['.md']);
  const skills = countFiles(path.resolve(ROOT, '.claude/skills'), ['.md']);
  const rules = countFiles(path.resolve(ROOT, '.claude/rules'), ['.md']);
  const briefs = countFiles(ROOT, ['BRIEF.md'], true);

  const testApi = countFiles(path.resolve(ROOT, 'apps/api/src'), ['.spec.ts'], true, {
    includeTests: true,
  });
  const testWeb = countFiles(path.resolve(ROOT, 'apps/web/src'), ['.test.ts', '.test.tsx'], true, {
    includeTests: true,
  });
  const testMobile = countFiles(
    path.resolve(ROOT, 'apps/mobile/src'),
    ['.test.ts', '.test.tsx'],
    true,
    { includeTests: true }
  );

  const docsCount = countFiles(path.resolve(ROOT, 'docs'), ['.md'], true);
  const adrDir = path.resolve(ROOT, 'docs/adr');
  const adrCount = fs.existsSync(adrDir)
    ? fs
        .readdirSync(adrDir, { withFileTypes: true })
        .filter((d) => d.isFile() && d.name.endsWith('.md') && d.name !== 'README.md').length
    : 0;

  return {
    backendModules,
    prismaModels,
    prismaEnums,
    schemaLines,
    frontendRoutes,
    frontendFeatures,
    uiComponents,
    mobileScreens,
    mobileComponents,
    sharedTypes,
    agents,
    skills,
    rules,
    briefs,
    testApi,
    testWeb,
    testMobile,
    docsCount,
    adrCount,
  };
}

// ── Output ──────────────────────────────────────────────────

function generate() {
  const s = gather();
  const now = new Date().toISOString().slice(0, 10);

  const md = `<!-- AUTO-GENERATED by scripts/generate-repo-snapshot.ts — DO NOT EDIT -->
# Repo Snapshot

Generated: ${now}

## Codebase

| Metric | Value |
|--------|-------|
| Backend modules | ${s.backendModules} |
| Prisma models | ${s.prismaModels} |
| Prisma enums | ${s.prismaEnums} |
| Schema lines | ${s.schemaLines} |
| Frontend routes | ${s.frontendRoutes} |
| Frontend feature dirs | ${s.frontendFeatures} |
| UI components (.tsx) | ${s.uiComponents} |
| Mobile screens (.tsx) | ${s.mobileScreens} |
| Mobile components (.tsx) | ${s.mobileComponents} |
| Shared type modules | ${s.sharedTypes} |
| Agent definitions | ${s.agents} |
| Skill definitions | ${s.skills} |
| Rule files | ${s.rules} |
| BRIEF.md files | ${s.briefs} |

## Testing

| Metric | Value |
|--------|-------|
| API test suites (.spec.ts) | ${s.testApi} |
| Web test files (.test.ts/tsx) | ${s.testWeb} |
| Mobile test files (.test.ts/tsx) | ${s.testMobile} |

## Documentation

| Metric | Value |
|--------|-------|
| docs/ files (.md) | ${s.docsCount} |
| ADR count | ${s.adrCount} |
`;

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, md, 'utf8');

  console.log(`\n✅ Generated ${path.relative(ROOT, OUTPUT)}`);
  console.log(`   Backend modules: ${s.backendModules}`);
  console.log(
    `   Prisma: ${s.prismaModels} models, ${s.prismaEnums} enums, ${s.schemaLines} lines`
  );
  console.log(`   Tests: ${s.testApi} API + ${s.testWeb} web + ${s.testMobile} mobile`);
  console.log(`   Docs: ${s.docsCount} files, ${s.adrCount} ADRs`);
}

generate();
