ALTER TABLE "School"
ADD COLUMN IF NOT EXISTS "housingAvailable" BOOLEAN,
ADD COLUMN IF NOT EXISTS "housingRequiredYears" INTEGER,
ADD COLUMN IF NOT EXISTS "percentLivingOnCampus" DECIMAL(5,2),
ADD COLUMN IF NOT EXISTS "mealPlanCost" INTEGER,
ADD COLUMN IF NOT EXISTS "campusSafetyServices" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "campusLifeSummary" JSONB;
