import { borderRadius, fontSize, fontWeight, spacing } from '@/utils/theme';
import { StyleSheet } from 'react-native';

export const S = StyleSheet.create({
  flex: { flex: 1 },
  headerSpacer: { width: 32 },
  typeCardAccent: { borderLeftWidth: 4 },
  quizProgress: { marginBottom: spacing.xl },
  questionStage: { minHeight: 280 },
  selectedOption: { borderWidth: 2 },
  defaultOption: { borderWidth: 1 },
  dimFillLeft: { borderTopLeftRadius: 4, borderBottomLeftRadius: 4 },
  dimFillRight: { borderTopRightRadius: 4, borderBottomRightRadius: 4 },
  resultActions: { marginTop: spacing.md, gap: spacing.sm },
  container: { flex: 1 },
  navigationHeader: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  navigationBack: {
    width: 56,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationTitle: {
    height: 44,
    textAlignVertical: 'center',
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    lineHeight: 44,
  },
  body: { paddingHorizontal: spacing.lg, paddingTop: spacing.lg },
  // Selection
  title: { fontSize: fontSize.xl, fontWeight: fontWeight.bold, marginBottom: spacing.lg },
  typeCard: { marginBottom: spacing.md },
  typeRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  typeIcon: {
    width: 52,
    height: 52,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  typeInfo: { flex: 1 },
  typeTitle: { fontSize: fontSize.base, fontWeight: fontWeight.semibold, marginBottom: spacing.xs },
  typeDesc: { fontSize: fontSize.sm, lineHeight: fontSize.sm * 1.5 },
  fullBtn: { width: '100%', marginTop: spacing.lg },
  // Quiz
  quizHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  iconBtn: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  progText: { fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  qNum: { fontSize: fontSize['2xl'], fontWeight: fontWeight.bold, marginBottom: spacing.sm },
  qText: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    lineHeight: fontSize.lg * 1.5,
    marginBottom: spacing.xl,
  },
  opt: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.lg,
    borderRadius: borderRadius.lg,
    gap: spacing.md,
  },
  optDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optText: { flex: 1, fontSize: fontSize.base, lineHeight: fontSize.base * 1.4 },
  navRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.xl,
    gap: spacing.md,
  },
  // Result
  rHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  rHeaderTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.semibold },
  hero: {
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    padding: spacing['2xl'],
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  mbtiType: {
    fontSize: fontSize['4xl'] + 8,
    fontWeight: fontWeight.bold,
    letterSpacing: 6,
    marginBottom: spacing.sm,
  },
  hollandCode: {
    fontSize: fontSize['4xl'],
    fontWeight: fontWeight.bold,
    letterSpacing: 4,
    marginBottom: spacing.md,
  },
  hollandTypes: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center' },
  heroTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  heroDesc: { fontSize: fontSize.sm, textAlign: 'center', lineHeight: fontSize.sm * 1.6 },
  // Dimensions
  sec: { marginBottom: spacing.xl },
  secLabel: { fontSize: fontSize.base, fontWeight: fontWeight.semibold, marginBottom: spacing.md },
  dimLabels: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.xs },
  dimLbl: { fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  dimTrack: { height: 10, borderRadius: 5, flexDirection: 'row', overflow: 'hidden' },
  dimFill: { height: '100%' },
  // Holland bars
  hBar: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.md, gap: spacing.sm },
  hKey: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  hKeyTxt: { fontSize: fontSize.sm, fontWeight: fontWeight.bold },
  hScore: { width: 32, fontSize: fontSize.sm, fontWeight: fontWeight.semibold, textAlign: 'right' },
  // Chips
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.full,
  },
  chipTxt: { fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  // List
  listRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  listText: { flex: 1, fontSize: fontSize.sm, lineHeight: fontSize.sm * 1.5 },
  // History
  histHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  histCard: { marginBottom: spacing.md },
  histRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  histIcon: {
    width: 44,
    height: 44,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  histTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  histSum: { fontSize: fontSize.lg, fontWeight: fontWeight.bold },
  histDate: { fontSize: fontSize.xs },
});
