import { StyleSheet } from 'react-native';
import { borderRadius, fontSize, fontWeight, spacing } from '@/utils/theme';

export const timelineLocalStyles = StyleSheet.create({
  container: { flex: 1 },
  flex: { flex: 1 },
  statusCard: { borderLeftWidth: 3 },
  schoolInfo: { flex: 1, marginRight: spacing.md, gap: spacing.sm },
  deadlineInfo: { alignItems: 'flex-end', gap: 2 },
  deleteRow: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: spacing.sm },
  eventHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  eventTitleRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  marginTopSm: { marginTop: spacing.sm },
  marginTopXl: { marginTop: spacing.xl },
  deleteButton: { alignSelf: 'flex-start', marginTop: spacing.sm },
  emptyGlobalText: {
    fontSize: fontSize.sm,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: spacing.xl,
  },
  noVerticalPadding: { paddingVertical: 0 },
  rowDivider: { borderBottomWidth: 1 },
  calendarDate: { alignItems: 'center', width: 44 },
  calendarMonth: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    textTransform: 'uppercase',
  },
  secondaryText: { fontSize: fontSize.xs, marginTop: 2 },
  statCard: { width: '47%' },
  centeredCard: { alignItems: 'center', gap: spacing.xs },
  centeredCaption: { fontSize: fontSize.xs, textAlign: 'center' },
  upcomingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    gap: spacing.md,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  overdueTask: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    borderWidth: 1,
    marginBottom: spacing.sm,
  },
  px: { paddingHorizontal: spacing.lg },
  tabs: { paddingHorizontal: spacing.lg, paddingVertical: spacing.md },
  headerCard: { marginTop: spacing.lg, marginBottom: spacing.sm },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between' },
  card: { marginBottom: spacing.md },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  name: { fontSize: fontSize.base, fontWeight: fontWeight.semibold },
  badges: { flexDirection: 'row', gap: spacing.xs },
  deadlineRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  deadlineTxt: { fontSize: fontSize.xs },
  daysLeft: { fontSize: fontSize.xs, fontWeight: fontWeight.medium },
  progRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, marginTop: spacing.md },
  progTxt: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    minWidth: 32,
    textAlign: 'right' as const,
  },
  expanded: {
    marginTop: spacing.lg,
    borderTopWidth: 1,
    paddingTop: spacing.md,
  },
  sectionHdr: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
    marginTop: spacing.sm,
  },
  sectionTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.semibold },
  globalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    gap: spacing.md,
  },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginBottom: spacing.xl },
});
