#!/usr/bin/env -S ts-node --transpile-only
/**
 * Step 2 of the data-driven prediction roadmap — fit a ridge logistic
 * regression with `logit(anchor)` as a FIXED OFFSET to decompose per-axis
 * log-odds shifts from real outcomes.
 *
 * Reads cached features from Step 1
 *   `apps/api/scripts/training-data/residual-lift-features-latest.json`
 * (generated by `learn-prediction-coefficients.ts --dump`).
 *
 * Outputs
 *   `apps/api/scripts/training-data/learned-coefficients-<ts>.json`
 *   `apps/api/scripts/training-data/learned-coefficients-latest.json`
 *   `apps/api/verification-report/learned-coefficients-<ts>.md`
 *
 * ────────────────────────────────────────────────────────────────────────────
 * Model
 * ────────────────────────────────────────────────────────────────────────────
 *
 *   P(admit_i = 1) = sigmoid( logit(anchor_i) + X_i · β )
 *
 * where:
 *   - `anchor_i` is the school's CDS overall admit rate (or round / intl /
 *     OOS override) — the same anchor used in Step 1.
 *   - `X_i` is a one-hot encoding of (gpa_band, sat_band, geo_band, round_band)
 *     plus binary hook flags (legacy, firstGen, athlete).
 *   - `β` is the vector of per-feature log-odds shifts we learn.
 *   - The base (one-hot dropped) levels are `gpa.25_50`, `sat.25_75`,
 *     `geo.unknown`, `round.RD`. Each learned coefficient is the log-odds
 *     shift RELATIVE TO that base.
 *
 * Why this parametrisation matches the hand-tuned engine:
 *   The engine composes hand-tuned multipliers multiplicatively. In log-odds
 *   space that's an additive shift — so `β[gpa.above_75]` directly maps to
 *   `log(engine.gpa.above_75 / engine.gpa.25_50)`. Reporting both side-by-side
 *   lets us see exactly where the hand-tuned values are too tight or too loose.
 *
 * Why ridge (L2) regularisation:
 *   n=~900-1000 over ~16 free coefficients. Without shrinkage some cells
 *   (e.g. `geo.intl`, `round.REA`) have tiny sample size and would over-fit.
 *   λ is selected by 5-fold cross-validation on weighted log-loss.
 *
 * Outcome convention (WAITLISTED handling):
 *   Each AdmissionCase is expanded into 1 or 2 training rows.
 *     ADMITTED   → 1 row with y=1, weight = propensity_weight
 *     REJECTED   → 1 row with y=0, weight = propensity_weight
 *     WAITLISTED → 2 rows: (y=1, w/2) + (y=0, w/2). Standard "half-credit"
 *                  treatment that lets the binomial likelihood be exact while
 *                  preserving the 0.5 expected-outcome convention from Step 1
 *                  / PR #299's empirical scorer.
 *
 * Optimisation:
 *   Pure-TS IRLS (Newton-Raphson on weighted binomial log-likelihood with the
 *   anchor offset and ridge penalty). Gauss-Jordan elimination for the small
 *   (~16x16) Hessian inverse — no external numerical lib.
 *
 * Run:
 *   pnpm --filter api exec tsx scripts/fit-residual-regression.ts
 *
 * Optional flags:
 *   --lambda <value>   skip CV, fit a single lambda
 *   --max-iter <n>     IRLS max iterations (default 50)
 *   --seed <n>         RNG seed for CV folds (default 17)
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT_DIR = resolve(__dirname, '..');
const TRAINING_DIR = resolve(ROOT_DIR, 'scripts/training-data');
const REPORT_DIR = resolve(ROOT_DIR, 'verification-report');
const CACHE_PATH = resolve(TRAINING_DIR, 'residual-lift-features-latest.json');
const TIMESTAMP = new Date().toISOString().replace(/[:.]/g, '-');

// CLI args
const argv = process.argv.slice(2);
function flag(name: string): string | undefined {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
}
const FIXED_LAMBDA = flag('--lambda') ? Number(flag('--lambda')) : undefined;
const MAX_ITER = flag('--max-iter') ? Number(flag('--max-iter')) : 50;
const SEED = flag('--seed') ? Number(flag('--seed')) : 17;
const LAMBDA_GRID = [0.01, 0.1, 1.0, 10.0, 100.0];

// ───────────────────────────────────────────────────────────────────────────
// Types — must mirror Step 1's TrainingRow exactly
// ───────────────────────────────────────────────────────────────────────────

interface TrainingRow {
  caseId: string;
  schoolNameNorm: string;
  schoolName: string;
  usNewsRank: number | null;
  acceptanceRate: number | null;
  intlAcceptanceRate: number | null;
  oosAcceptanceRate: number | null;
  edAcceptanceRate: number | null;
  eaAcceptanceRate: number | null;
  sat25: number | null;
  sat75: number | null;
  gpaDistribution: Record<string, number> | null;
  state: string | null;
  isPrivate: boolean;
  gpa4: number | null;
  bestSat: number | null;
  applyingTestOptional: boolean;
  isInternational: boolean;
  nationality: string | null;
  highSchoolState: string | null;
  isLegacy: boolean;
  isFirstGen: boolean;
  recruitedAthlete: boolean;
  applicationRound: string;
  applicationYear: number;
  result: 'ADMITTED' | 'REJECTED' | 'WAITLISTED';
  y: number;
}

type GpaBand = 'below_25' | '25_50' | '50_75' | 'above_75' | 'unknown';
type SatBand = 'below_25' | '25_75' | 'above_75' | 'TO' | 'unknown';
type GeoBand =
  | 'intl'
  | 'oos_public'
  | 'in_state_public'
  | 'private'
  | 'unknown';
type RoundBand = 'ED' | 'ED2' | 'EA' | 'REA' | 'RD' | 'unknown';
type Tier = 'T5' | 'T6_20' | 'T21_50' | 'T51_100' | 'T100plus';

// ───────────────────────────────────────────────────────────────────────────
// Bucketing — must MATCH Step 1 exactly so β maps to Step 1's cells
// ───────────────────────────────────────────────────────────────────────────

function computeAnchor(row: TrainingRow): number | null {
  if (row.applicationRound === 'ED' && row.edAcceptanceRate != null) {
    return row.edAcceptanceRate > 1
      ? row.edAcceptanceRate / 100
      : row.edAcceptanceRate;
  }
  if (row.applicationRound === 'EA' && row.eaAcceptanceRate != null) {
    return row.eaAcceptanceRate > 1
      ? row.eaAcceptanceRate / 100
      : row.eaAcceptanceRate;
  }
  if (row.isInternational && row.intlAcceptanceRate != null) {
    return row.intlAcceptanceRate > 1
      ? row.intlAcceptanceRate / 100
      : row.intlAcceptanceRate;
  }
  if (
    row.state != null &&
    row.highSchoolState != null &&
    row.state !== row.highSchoolState &&
    row.oosAcceptanceRate != null
  ) {
    return row.oosAcceptanceRate > 1
      ? row.oosAcceptanceRate / 100
      : row.oosAcceptanceRate;
  }
  if (row.acceptanceRate != null) {
    return row.acceptanceRate > 1
      ? row.acceptanceRate / 100
      : row.acceptanceRate;
  }
  return null;
}

function gpaBandFor(row: TrainingRow): GpaBand {
  if (row.gpa4 == null) return 'unknown';
  if (row.gpaDistribution) {
    const bands = [
      { key: '<3.00', lo: 0, hi: 3.0 },
      { key: '3.00-3.24', lo: 3.0, hi: 3.25 },
      { key: '3.25-3.49', lo: 3.25, hi: 3.5 },
      { key: '3.50-3.74', lo: 3.5, hi: 3.75 },
      { key: '3.75-4.00', lo: 3.75, hi: 4.01 },
    ];
    const raw = bands.map((b) => Number(row.gpaDistribution?.[b.key] ?? 0));
    const total = raw.reduce((a, b) => a + b, 0);
    if (total > 0) {
      const norm =
        total > 2 ? raw.map((v) => v / 100) : raw.map((v) => v / total);
      let cum = 0;
      let pct = 0;
      let found = false;
      for (let i = 0; i < bands.length; i++) {
        if (row.gpa4 >= bands[i].hi) {
          cum += norm[i];
        } else if (row.gpa4 >= bands[i].lo) {
          const frac = (row.gpa4 - bands[i].lo) / (bands[i].hi - bands[i].lo);
          pct = cum + norm[i] * frac;
          found = true;
          break;
        } else {
          pct = cum;
          found = true;
          break;
        }
      }
      if (!found) pct = cum;
      if (pct < 0.25) return 'below_25';
      if (pct < 0.5) return '25_50';
      if (pct < 0.75) return '50_75';
      return 'above_75';
    }
  }
  if (row.sat25 && row.sat75) {
    const equivSat = (row.gpa4 - 2.0) * 100 + 1000;
    if (equivSat < row.sat25) return 'below_25';
    if (equivSat >= row.sat75) return 'above_75';
    const mid = (row.sat25 + row.sat75) / 2;
    return equivSat >= mid ? '50_75' : '25_50';
  }
  return 'unknown';
}

function satBandFor(row: TrainingRow): SatBand {
  if (row.applyingTestOptional || row.bestSat == null) return 'TO';
  if (!row.sat25 || !row.sat75) return 'unknown';
  if (row.bestSat < row.sat25) return 'below_25';
  if (row.bestSat >= row.sat75) return 'above_75';
  return '25_75';
}

function geoBandFor(row: TrainingRow): GeoBand {
  if (row.isInternational) return 'intl';
  if (row.isPrivate) return 'private';
  if (!row.state || !row.highSchoolState) return 'unknown';
  if (row.highSchoolState === row.state) return 'in_state_public';
  return 'oos_public';
}

function roundBandFor(row: TrainingRow): RoundBand {
  const r = row.applicationRound;
  if (r === 'ED' || r === 'EARLY_DECISION') return 'ED';
  if (r === 'ED2' || r === 'ED_II') return 'ED2';
  if (r === 'EA' || r === 'EARLY_ACTION') return 'EA';
  if (r === 'REA' || r === 'SCEA') return 'REA';
  if (r === 'RD' || r === 'REGULAR' || r === 'REGULAR_DECISION') return 'RD';
  return 'unknown';
}

function tierFor(row: TrainingRow): Tier {
  const r = row.usNewsRank ?? 999;
  if (r <= 5) return 'T5';
  if (r <= 20) return 'T6_20';
  if (r <= 50) return 'T21_50';
  if (r <= 100) return 'T51_100';
  return 'T100plus';
}

const POPULATION_ADMIT_RATE: Record<Tier, number> = {
  T5: 0.05,
  T6_20: 0.1,
  T21_50: 0.25,
  T51_100: 0.55,
  T100plus: 0.7,
};

function computePropensityWeights(rows: TrainingRow[]): number[] {
  const byTier: Record<string, { n: number; admits: number }> = {};
  for (const r of rows) {
    const t = tierFor(r);
    byTier[t] = byTier[t] || { n: 0, admits: 0 };
    byTier[t].n++;
    byTier[t].admits += r.y;
  }
  const sampleRateByTier: Record<string, number> = {};
  for (const t of Object.keys(byTier)) {
    sampleRateByTier[t] = byTier[t].admits / byTier[t].n;
  }
  return rows.map((r) => {
    const t = tierFor(r);
    const popP = POPULATION_ADMIT_RATE[t];
    const sampP = sampleRateByTier[t];
    const isAdmit = r.y >= 0.5;
    const w = isAdmit
      ? sampP > 0
        ? popP / sampP
        : 1
      : (1 - popP) / (1 - sampP);
    return Math.max(0.05, Math.min(5, w));
  });
}

// ───────────────────────────────────────────────────────────────────────────
// Feature encoding
// ───────────────────────────────────────────────────────────────────────────

// Base levels (dropped from one-hot, become the intercept reference):
//   gpa: 25_50    sat: 25_75    geo: unknown    round: RD
//
// Anything else is encoded as a binary feature. This gives us 16 features
// from the band axes + 3 hook indicators = 19 features + intercept (1) = 20
// columns in X.
const FEATURE_NAMES = [
  // gpa: 4 (drop 25_50)
  'gpa.below_25',
  'gpa.50_75',
  'gpa.above_75',
  'gpa.unknown',
  // sat: 4 (drop 25_75)
  'sat.below_25',
  'sat.above_75',
  'sat.TO',
  'sat.unknown',
  // geo: 4 (drop unknown)
  'geo.intl',
  'geo.oos_public',
  'geo.in_state_public',
  'geo.private',
  // round: 5 (drop RD)
  'round.ED',
  'round.ED2',
  'round.EA',
  'round.REA',
  'round.unknown',
  // hooks
  'hook.legacy',
  'hook.firstGen',
  'hook.athlete',
] as const;
type FeatureName = (typeof FEATURE_NAMES)[number];
const N_FEATURES = FEATURE_NAMES.length;

function encodeRow(row: TrainingRow): {
  features: Float64Array;
  anchor: number;
} | null {
  const anchor = computeAnchor(row);
  if (anchor == null || anchor <= 0 || anchor >= 1) return null;

  const x = new Float64Array(N_FEATURES);
  const setOne = (name: FeatureName) => {
    const idx = FEATURE_NAMES.indexOf(name);
    if (idx >= 0) x[idx] = 1;
  };
  const gpa = gpaBandFor(row);
  if (gpa !== '25_50') setOne(`gpa.${gpa}` as FeatureName);
  const sat = satBandFor(row);
  if (sat !== '25_75') setOne(`sat.${sat}` as FeatureName);
  const geo = geoBandFor(row);
  if (geo !== 'unknown') setOne(`geo.${geo}` as FeatureName);
  const round = roundBandFor(row);
  if (round !== 'RD') setOne(`round.${round}` as FeatureName);
  if (row.isLegacy) setOne('hook.legacy');
  if (row.isFirstGen) setOne('hook.firstGen');
  if (row.recruitedAthlete) setOne('hook.athlete');

  return { features: x, anchor };
}

// ───────────────────────────────────────────────────────────────────────────
// Pure-TS numerical helpers — Gauss-Jordan for the (N_FEATURES+1)x(N_FEATURES+1)
// matrix inverse used in IRLS / ridge. Includes the intercept.
// ───────────────────────────────────────────────────────────────────────────

const D = N_FEATURES + 1; // intercept + features

/** In-place LU-style solve: returns `A^(-1) b`. Both A and b mutated. */
function solveLinearSystem(A: Float64Array, b: Float64Array): Float64Array {
  // A is row-major D×D, b is length D. Solve A x = b for x.
  // Standard partial-pivoting Gaussian elimination.
  for (let col = 0; col < D; col++) {
    // Pivot
    let maxRow = col;
    let maxAbs = Math.abs(A[col * D + col]);
    for (let r = col + 1; r < D; r++) {
      const v = Math.abs(A[r * D + col]);
      if (v > maxAbs) {
        maxAbs = v;
        maxRow = r;
      }
    }
    if (maxAbs < 1e-12) {
      throw new Error(
        `Singular matrix at column ${col} (max abs pivot ${maxAbs.toExponential()})`,
      );
    }
    if (maxRow !== col) {
      for (let c = 0; c < D; c++) {
        const tmp = A[col * D + c];
        A[col * D + c] = A[maxRow * D + c];
        A[maxRow * D + c] = tmp;
      }
      const tmpB = b[col];
      b[col] = b[maxRow];
      b[maxRow] = tmpB;
    }
    // Eliminate
    const pivot = A[col * D + col];
    for (let r = 0; r < D; r++) {
      if (r === col) continue;
      const factor = A[r * D + col] / pivot;
      if (factor === 0) continue;
      for (let c = col; c < D; c++) {
        A[r * D + c] -= factor * A[col * D + c];
      }
      b[r] -= factor * b[col];
    }
  }
  // Now A is diagonal; back-substitute
  const x = new Float64Array(D);
  for (let i = 0; i < D; i++) {
    x[i] = b[i] / A[i * D + i];
  }
  return x;
}

// ───────────────────────────────────────────────────────────────────────────
// IRLS — weighted logistic regression with offset + ridge
// ───────────────────────────────────────────────────────────────────────────

interface FitResult {
  beta: Float64Array; // length D (intercept first, then features)
  iterations: number;
  converged: boolean;
  trainLogLoss: number;
}

function sigmoid(z: number): number {
  if (z >= 0) {
    const e = Math.exp(-z);
    return 1 / (1 + e);
  } else {
    const e = Math.exp(z);
    return e / (1 + e);
  }
}

function fitIRLS(
  X: Float64Array, // n × N_FEATURES row-major
  offset: Float64Array, // n  (logit(anchor) per row)
  y: Float64Array, // n  (binary 0/1)
  w: Float64Array, // n  (sample weight; for WL-split rows already halved)
  lambda: number,
  maxIter = MAX_ITER,
  tol = 1e-6,
): FitResult {
  const n = y.length;
  let beta = new Float64Array(D); // β₀ + β₁..βₚ
  let iter = 0;
  let prevLL = -Infinity;

  for (iter = 0; iter < maxIter; iter++) {
    // η = offset + intercept + X β
    const eta = new Float64Array(n);
    const p = new Float64Array(n);
    const Wdiag = new Float64Array(n);
    const z = new Float64Array(n); // working response
    for (let i = 0; i < n; i++) {
      let e = offset[i] + beta[0];
      for (let j = 0; j < N_FEATURES; j++) {
        e += X[i * N_FEATURES + j] * beta[j + 1];
      }
      eta[i] = e;
      const pi = sigmoid(e);
      p[i] = pi;
      const wi = w[i] * pi * (1 - pi);
      Wdiag[i] = wi;
      // Working response: η + (y - p) / (p(1-p)). Clamp denom away from 0 to
      // avoid blow-up at saturated predictions. (Original ternary had a
      // precedence bug — `e + denom > 1e-9` was parsed as `(e + denom) > 1e-9`
      // instead of `denom > 1e-9`. The fallback was rarely hit either way,
      // so this fix is mostly defensive.)
      const denom = Math.max(pi * (1 - pi), 1e-6);
      z[i] = e + (y[i] - pi) / denom;
    }

    // Build normal equations: (X'_aug W X_aug + λI_p) β = X'_aug W (z - offset)
    // X_aug = [1 | X], so X_aug β includes intercept.
    // Ridge penalty applied to β₁..βₚ only (NOT the intercept).
    const A = new Float64Array(D * D);
    const b = new Float64Array(D);

    for (let i = 0; i < n; i++) {
      const wi = Wdiag[i];
      const ti = z[i] - offset[i]; // we move offset to RHS
      // x_aug = [1, X[i,:]]
      // A += wi * x_aug x_aug^T;   b += wi * ti * x_aug
      // Index 0 is intercept; 1..D-1 is features
      A[0] += wi;
      b[0] += wi * ti;
      for (let j = 0; j < N_FEATURES; j++) {
        const xj = X[i * N_FEATURES + j];
        if (xj === 0) continue;
        const wxj = wi * xj;
        A[j + 1] += wxj; // A[0][j+1]
        A[(j + 1) * D] += wxj; // A[j+1][0]
        b[j + 1] += wxj * ti;
        // upper-triangular feature×feature block
        for (let k = j; k < N_FEATURES; k++) {
          const xk = X[i * N_FEATURES + k];
          if (xk === 0) continue;
          const v = wxj * xk;
          A[(j + 1) * D + (k + 1)] += v;
          if (k !== j) A[(k + 1) * D + (j + 1)] += v;
        }
      }
    }
    // Ridge (NOT on intercept)
    for (let j = 1; j < D; j++) {
      A[j * D + j] += lambda;
    }

    const newBeta = solveLinearSystem(A, b);

    // Convergence
    let maxDelta = 0;
    for (let j = 0; j < D; j++) {
      const d = Math.abs(newBeta[j] - beta[j]);
      if (d > maxDelta) maxDelta = d;
    }
    beta = newBeta;
    if (maxDelta < tol) {
      break;
    }
    // Optional: track log-likelihood to detect divergence
    let ll = 0;
    for (let i = 0; i < n; i++) {
      let e = offset[i] + beta[0];
      for (let j = 0; j < N_FEATURES; j++) {
        e += X[i * N_FEATURES + j] * beta[j + 1];
      }
      const pi = sigmoid(e);
      const yi = y[i];
      ll +=
        w[i] *
        (yi * Math.log(Math.max(pi, 1e-12)) +
          (1 - yi) * Math.log(Math.max(1 - pi, 1e-12)));
    }
    if (iter > 5 && ll < prevLL - 1) {
      console.warn(
        `  WARN: IRLS log-likelihood decreased at iter ${iter} (${prevLL.toFixed(3)} → ${ll.toFixed(3)}); damping not implemented — likely fine for λ ≥ 0.01 but worth a look.`,
      );
    }
    prevLL = ll;
  }

  // Final log-loss
  let logLoss = 0;
  let totalW = 0;
  for (let i = 0; i < n; i++) {
    let e = offset[i] + beta[0];
    for (let j = 0; j < N_FEATURES; j++) {
      e += X[i * N_FEATURES + j] * beta[j + 1];
    }
    const pi = sigmoid(e);
    const yi = y[i];
    logLoss -=
      w[i] *
      (yi * Math.log(Math.max(pi, 1e-12)) +
        (1 - yi) * Math.log(Math.max(1 - pi, 1e-12)));
    totalW += w[i];
  }
  return {
    beta,
    iterations: iter + 1,
    converged: iter < maxIter - 1,
    trainLogLoss: totalW > 0 ? logLoss / totalW : Infinity,
  };
}

// ───────────────────────────────────────────────────────────────────────────
// WAITLISTED expansion — split into 2 rows (half admit + half reject)
// ───────────────────────────────────────────────────────────────────────────

interface ExpandedRow {
  features: Float64Array;
  offset: number; // logit(anchor)
  y: 0 | 1;
  weight: number;
}

function expand(rows: TrainingRow[], weights: number[]): ExpandedRow[] {
  const out: ExpandedRow[] = [];
  for (let i = 0; i < rows.length; i++) {
    const enc = encodeRow(rows[i]);
    if (!enc) continue;
    const offset = Math.log(enc.anchor / (1 - enc.anchor));
    const w = weights[i];
    const r = rows[i];
    if (r.result === 'ADMITTED') {
      out.push({ features: enc.features, offset, y: 1, weight: w });
    } else if (r.result === 'REJECTED') {
      out.push({ features: enc.features, offset, y: 0, weight: w });
    } else {
      // WAITLISTED → split into (1, w/2) + (0, w/2)
      out.push({ features: enc.features, offset, y: 1, weight: w / 2 });
      out.push({ features: enc.features, offset, y: 0, weight: w / 2 });
    }
  }
  return out;
}

// ───────────────────────────────────────────────────────────────────────────
// 5-fold cross-validation for λ
// ───────────────────────────────────────────────────────────────────────────

function makeRng(seed: number): () => number {
  let state = seed | 0;
  return () => {
    state = (state + 0x6d2b79f5) | 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle<T>(arr: T[], rng: () => number): T[] {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

function buildMatrices(rows: ExpandedRow[]): {
  X: Float64Array;
  offset: Float64Array;
  y: Float64Array;
  w: Float64Array;
} {
  const n = rows.length;
  const X = new Float64Array(n * N_FEATURES);
  const offset = new Float64Array(n);
  const y = new Float64Array(n);
  const w = new Float64Array(n);
  for (let i = 0; i < n; i++) {
    X.set(rows[i].features, i * N_FEATURES);
    offset[i] = rows[i].offset;
    y[i] = rows[i].y;
    w[i] = rows[i].weight;
  }
  return { X, offset, y, w };
}

function weightedLogLoss(rows: ExpandedRow[], beta: Float64Array): number {
  let logLoss = 0;
  let totalW = 0;
  for (const r of rows) {
    let e = r.offset + beta[0];
    for (let j = 0; j < N_FEATURES; j++) {
      e += r.features[j] * beta[j + 1];
    }
    const p = sigmoid(e);
    logLoss -=
      r.weight *
      (r.y * Math.log(Math.max(p, 1e-12)) +
        (1 - r.y) * Math.log(Math.max(1 - p, 1e-12)));
    totalW += r.weight;
  }
  return totalW > 0 ? logLoss / totalW : Infinity;
}

function crossValidate(
  rows: ExpandedRow[],
  lambdas: number[],
  k: number,
  seed: number,
): Array<{ lambda: number; meanCvLogLoss: number; foldLogLosses: number[] }> {
  const rng = makeRng(seed);
  const shuffled = shuffle(rows, rng);
  const n = shuffled.length;
  const foldSize = Math.floor(n / k);

  return lambdas.map((lambda) => {
    const foldLogLosses: number[] = [];
    for (let f = 0; f < k; f++) {
      const start = f * foldSize;
      const end = f === k - 1 ? n : start + foldSize;
      const valid = shuffled.slice(start, end);
      const train = [...shuffled.slice(0, start), ...shuffled.slice(end)];
      const m = buildMatrices(train);
      const fit = fitIRLS(m.X, m.offset, m.y, m.w, lambda);
      const cvLL = weightedLogLoss(valid, fit.beta);
      foldLogLosses.push(cvLL);
    }
    const meanCvLogLoss =
      foldLogLosses.reduce((a, b) => a + b, 0) / foldLogLosses.length;
    return { lambda, meanCvLogLoss, foldLogLosses };
  });
}

// ───────────────────────────────────────────────────────────────────────────
// Hand-tuned reference (must match Step 1)
// ───────────────────────────────────────────────────────────────────────────

const ENGINE_HAND_TUNED_MULT: Record<string, number> = {
  // base levels are 1.0 (gpa.25_50, sat.25_75, geo.unknown, round.RD)
  'gpa.below_25': 0.5,
  'gpa.50_75': 1.1,
  'gpa.above_75': 1.3,
  'gpa.unknown': 1.0,
  'sat.below_25': 0.5,
  'sat.above_75': 1.3,
  'sat.TO': 0.85,
  'sat.unknown': 1.0,
  'geo.intl': 0.4,
  'geo.oos_public': 0.7,
  'geo.in_state_public': 1.5,
  'geo.private': 1.0,
  'round.ED': 2.5,
  'round.ED2': 1.8,
  'round.EA': 1.2,
  'round.REA': 1.2,
  'round.unknown': 1.0,
  'hook.legacy': 3.0, // Arcidiacono OR=8.5 → log-odds +2.14 (approx ×exp(2.14)/2.5 base ≈ ×3)
  'hook.firstGen': 1.0,
  'hook.athlete': 5.0,
};

// ───────────────────────────────────────────────────────────────────────────
// Report writer
// ───────────────────────────────────────────────────────────────────────────

interface ReportInputs {
  rows: TrainingRow[];
  expanded: ExpandedRow[];
  cvResults: Array<{
    lambda: number;
    meanCvLogLoss: number;
    foldLogLosses: number[];
  }>;
  bestLambda: number;
  finalFit: FitResult;
}

function writeReport(inputs: ReportInputs) {
  mkdirSync(REPORT_DIR, { recursive: true });
  const path = resolve(REPORT_DIR, `learned-coefficients-${TIMESTAMP}.md`);

  const { rows, expanded, cvResults, bestLambda, finalFit } = inputs;
  const lines: string[] = [];
  lines.push(`# Learned residual-lift coefficients — ${TIMESTAMP}`);
  lines.push('');
  lines.push(
    `**Sample**: ${rows.length} cached training rows from \`residual-lift-features-latest.json\` (Step 1 output). After WAITLISTED-split expansion: ${expanded.length} training rows.`,
  );
  lines.push('');
  lines.push(
    `**Model**: \`P(admit) = sigmoid( logit(anchor) + X·β )\` where X encodes (gpa_band, sat_band, geo_band, round_band) plus hook flags. Base levels: \`gpa.25_50\` / \`sat.25_75\` / \`geo.unknown\` / \`round.RD\`. Each learned coefficient is the log-odds shift RELATIVE to the base.`,
  );
  lines.push('');
  lines.push(
    `**Fitting**: weighted IRLS (Newton-Raphson on binomial log-likelihood with anchor offset and ridge L2 penalty). Sample weights = propensity from Step 1 (capped [0.05, 5]). WAITLISTED rows split into half-admit + half-reject.`,
  );
  lines.push('');
  lines.push('## Cross-validation (5-fold weighted log-loss)');
  lines.push('');
  lines.push('| λ | mean CV log-loss | fold log-losses |');
  lines.push('|---|---|---|');
  for (const c of cvResults) {
    lines.push(
      `| ${c.lambda} | ${c.meanCvLogLoss.toFixed(4)} | ${c.foldLogLosses.map((x) => x.toFixed(3)).join(', ')} |`,
    );
  }
  lines.push('');
  lines.push(`**Selected λ**: ${bestLambda} (lowest mean CV log-loss).`);
  lines.push(
    `**Final fit**: ${finalFit.converged ? 'converged' : 'did NOT converge'} in ${finalFit.iterations} iterations; in-sample log-loss ${finalFit.trainLogLoss.toFixed(4)}.`,
  );
  lines.push('');
  lines.push('## Learned coefficients vs hand-tuned engine multipliers');
  lines.push('');
  lines.push(
    'Each row: log-odds shift `β` (learned) → multiplier-equivalent `exp(β)`. Hand-tuned multiplier shown for comparison.',
  );
  lines.push('');
  lines.push(
    '| feature | learned β | learned mult (e^β) | hand-tuned mult | delta (× scale) |',
  );
  lines.push('|---|---|---|---|---|');
  lines.push(
    `| (intercept) | ${finalFit.beta[0].toFixed(3)} | ${Math.exp(finalFit.beta[0]).toFixed(2)}× | — | — |`,
  );
  for (let j = 0; j < N_FEATURES; j++) {
    const name = FEATURE_NAMES[j];
    const beta = finalFit.beta[j + 1];
    const mult = Math.exp(beta);
    const handTuned = ENGINE_HAND_TUNED_MULT[name] ?? 1.0;
    const delta = mult - handTuned;
    lines.push(
      `| ${name} | ${beta >= 0 ? '+' : ''}${beta.toFixed(3)} | ${mult.toFixed(2)}× | ${handTuned.toFixed(2)}× | ${delta >= 0 ? '+' : ''}${delta.toFixed(2)} |`,
    );
  }

  lines.push('');
  lines.push('## Biggest gaps between learned and hand-tuned');
  lines.push('');
  const gaps = FEATURE_NAMES.map((name, j) => {
    const learnedMult = Math.exp(finalFit.beta[j + 1]);
    const handTuned = ENGINE_HAND_TUNED_MULT[name] ?? 1.0;
    return { name, learnedMult, handTuned, delta: learnedMult - handTuned };
  })
    .filter((g) => Math.abs(g.delta) > 0.2)
    .sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta));

  if (gaps.length === 0) {
    lines.push(
      '_No features with |delta| > 0.2× — learned coefficients broadly agree with hand-tuned._',
    );
  } else {
    for (const g of gaps) {
      const direction =
        g.delta > 0
          ? 'engine UNDER-credits this feature'
          : 'engine OVER-credits this feature';
      lines.push(
        `- **${g.name}**: learned ${g.learnedMult.toFixed(2)}× vs hand-tuned ${g.handTuned.toFixed(2)}× — Δ ${g.delta >= 0 ? '+' : ''}${g.delta.toFixed(2)} (${direction})`,
      );
    }
  }

  lines.push('');
  lines.push('## How to read');
  lines.push('');
  lines.push(
    '- A learned multiplier > 1 means "this feature increases admit log-odds vs the base level"; < 1 means decrease.',
  );
  lines.push(
    "- The comparison with `ENGINE_HAND_TUNED_MULT` is *per-feature* — these are the multipliers that would replace the engine's hand-tuned per-axis values. Composing them multiplicatively reproduces the engine's anchor × Π multiplier path.",
  );
  lines.push(
    '- Coefficients should be interpreted as **directional signals**, not point estimates, when 95% CIs are wide. Step 3 will add bootstrap CIs for each coefficient.',
  );
  lines.push('');
  lines.push('## Caveats');
  lines.push('');
  lines.push(
    '- **Sample is small** (n=' +
      rows.length +
      ' before expansion). Cells with rare combinations (e.g. `geo.intl`, `round.REA`) are mostly informed by ridge shrinkage toward 0; their learned coefficients are conservative.',
  );
  lines.push(
    '- **Selection bias is only partially corrected** by per-tier propensity weights. Within-tier selection (who self-reports a rejection) is not modeled. Step 3 will explore per-cell propensity.',
  );
  lines.push(
    '- **Anchor resolution is simplified** — same as Step 1: school-level CDS rate with round / intl / OOS overrides. No CDS-band cell lookup.',
  );
  lines.push(
    "- **Hook coefficients** in the hand-tuned reference are illustrative; the engine's actual hook handling lives in `prediction-hook-modifiers.service.ts` and uses tier-specific log-odds shifts.",
  );
  lines.push(
    `- **Pure-TS IRLS** with partial-pivoting Gauss-Jordan inverse — no external numerical lib. ${D}×${D} system is trivial for current n. Converges in ~5-15 iterations for λ ≥ 0.01.`,
  );

  writeFileSync(path, lines.join('\n'));
  console.log(`Wrote report → ${path}`);
}

// ───────────────────────────────────────────────────────────────────────────
// Main
// ───────────────────────────────────────────────────────────────────────────

function main() {
  if (!existsSync(CACHE_PATH)) {
    console.error(
      `No cached features at ${CACHE_PATH}. Run learn-prediction-coefficients.ts --dump first.`,
    );
    process.exit(1);
  }
  const payload = JSON.parse(readFileSync(CACHE_PATH, 'utf8'));
  const rows = payload.rows as TrainingRow[];
  console.log(`Loaded ${rows.length} training rows.`);

  console.log('Computing propensity weights...');
  const weights = computePropensityWeights(rows);
  const wMin = Math.min(...weights);
  const wMax = Math.max(...weights);
  console.log(
    `  weight range: [${wMin.toFixed(2)}, ${wMax.toFixed(2)}] (capped at [0.05, 5])`,
  );

  console.log('Expanding WAITLISTED rows (half admit + half reject)...');
  const expanded = expand(rows, weights);
  console.log(`  expanded ${rows.length} → ${expanded.length} rows.`);

  let bestLambda: number;
  let cvResults: ReturnType<typeof crossValidate>;
  if (FIXED_LAMBDA != null) {
    console.log(`Fixed λ=${FIXED_LAMBDA} (CV skipped per --lambda flag).`);
    cvResults = [
      { lambda: FIXED_LAMBDA, meanCvLogLoss: NaN, foldLogLosses: [] },
    ];
    bestLambda = FIXED_LAMBDA;
  } else {
    console.log(`Running 5-fold CV over λ grid [${LAMBDA_GRID.join(', ')}]...`);
    cvResults = crossValidate(expanded, LAMBDA_GRID, 5, SEED);
    bestLambda = cvResults
      .slice()
      .sort((a, b) => a.meanCvLogLoss - b.meanCvLogLoss)[0].lambda;
    for (const c of cvResults) {
      console.log(
        `  λ=${c.lambda.toFixed(3)}: mean CV log-loss = ${c.meanCvLogLoss.toFixed(4)} ${c.lambda === bestLambda ? '← best' : ''}`,
      );
    }
  }

  console.log(`Final fit on full data with λ=${bestLambda}...`);
  const m = buildMatrices(expanded);
  const finalFit = fitIRLS(m.X, m.offset, m.y, m.w, bestLambda);
  console.log(
    `  ${finalFit.converged ? 'CONVERGED' : 'DID NOT CONVERGE'} in ${finalFit.iterations} iterations; train log-loss ${finalFit.trainLogLoss.toFixed(4)}.`,
  );

  // Output
  mkdirSync(TRAINING_DIR, { recursive: true });
  const coefPayload = {
    generatedAt: new Date().toISOString(),
    bestLambda,
    cvResults,
    iterations: finalFit.iterations,
    converged: finalFit.converged,
    trainLogLoss: finalFit.trainLogLoss,
    sampleSize: { rows: rows.length, expanded: expanded.length },
    baseLevels: {
      gpa: '25_50',
      sat: '25_75',
      geo: 'unknown',
      round: 'RD',
    },
    coefficients: {
      intercept: finalFit.beta[0],
      ...Object.fromEntries(
        FEATURE_NAMES.map((name, j) => [name, finalFit.beta[j + 1]]),
      ),
    },
    multipliers: {
      intercept: Math.exp(finalFit.beta[0]),
      ...Object.fromEntries(
        FEATURE_NAMES.map((name, j) => [name, Math.exp(finalFit.beta[j + 1])]),
      ),
    },
  };
  const versioned = resolve(
    TRAINING_DIR,
    `learned-coefficients-${TIMESTAMP}.json`,
  );
  const latest = resolve(TRAINING_DIR, 'learned-coefficients-latest.json');
  writeFileSync(versioned, JSON.stringify(coefPayload, null, 2));
  writeFileSync(latest, JSON.stringify(coefPayload, null, 2));
  console.log(`  wrote coefficients → ${versioned}`);
  console.log(`  also wrote → ${latest}`);

  writeReport({ rows, expanded, cvResults, bestLambda, finalFit });

  console.log('\nDone.');
}

main();
