import type { ThemeId } from '../types';

// Partial theme — only colors + decorations that vary per preset.
// Font, fontSize, spacing are merged from template defaults.
export interface ThemePreset {
  id: ThemeId;
  name: string;
  category: 'professional' | 'modern' | 'creative' | 'minimal' | 'classic';
  primary: string;
  secondary: string;
  background: string;
  sidebarBg: string;
  sidebarText: string;
  headerBg: string;
  headerText: string;
  text: string;
  textLight: string;
  border: string;
}

export const THEME_PRESETS: Record<ThemeId, ThemePreset> = {
  navy: {
    id: 'navy',
    name: 'Navy',
    category: 'professional',
    primary: '#1e3a5f',
    secondary: '#2563eb',
    background: '#ffffff',
    sidebarBg: '#f0f4f8',
    sidebarText: '#1e3a5f',
    headerBg: '#1e3a5f',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  charcoal: {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'professional',
    primary: '#333333',
    secondary: '#555555',
    background: '#ffffff',
    sidebarBg: '#f5f5f5',
    sidebarText: '#333333',
    headerBg: '#333333',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#666666',
    border: '#d4d4d4',
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    category: 'professional',
    primary: '#2d5016',
    secondary: '#4d7c0f',
    background: '#ffffff',
    sidebarBg: '#f0f5ec',
    sidebarText: '#2d5016',
    headerBg: '#2d5016',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  teal: {
    id: 'teal',
    name: 'Teal',
    category: 'modern',
    primary: '#0d9488',
    secondary: '#14b8a6',
    background: '#ffffff',
    sidebarBg: '#f0fdfa',
    sidebarText: '#0d9488',
    headerBg: '#0d9488',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  indigo: {
    id: 'indigo',
    name: 'Indigo',
    category: 'modern',
    primary: '#4f46e5',
    secondary: '#6366f1',
    background: '#ffffff',
    sidebarBg: '#eef2ff',
    sidebarText: '#4f46e5',
    headerBg: '#4f46e5',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  coral: {
    id: 'coral',
    name: 'Coral',
    category: 'modern',
    primary: '#e11d48',
    secondary: '#f43f5e',
    background: '#ffffff',
    sidebarBg: '#fff1f2',
    sidebarText: '#e11d48',
    headerBg: '#e11d48',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  amber: {
    id: 'amber',
    name: 'Amber',
    category: 'creative',
    primary: '#d97706',
    secondary: '#f59e0b',
    background: '#ffffff',
    sidebarBg: '#fffbeb',
    sidebarText: '#92400e',
    headerBg: '#d97706',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  violet: {
    id: 'violet',
    name: 'Violet',
    category: 'creative',
    primary: '#7c3aed',
    secondary: '#8b5cf6',
    background: '#ffffff',
    sidebarBg: '#f5f3ff',
    sidebarText: '#7c3aed',
    headerBg: '#7c3aed',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    category: 'creative',
    primary: '#be185d',
    secondary: '#ec4899',
    background: '#ffffff',
    sidebarBg: '#fdf2f8',
    sidebarText: '#be185d',
    headerBg: '#be185d',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  black: {
    id: 'black',
    name: 'Black',
    category: 'minimal',
    primary: '#000000',
    secondary: '#374151',
    background: '#ffffff',
    sidebarBg: '#ffffff',
    sidebarText: '#000000',
    headerBg: '#000000',
    headerText: '#ffffff',
    text: '#000000',
    textLight: '#4b5563',
    border: '#000000',
  },
  slate: {
    id: 'slate',
    name: 'Slate',
    category: 'minimal',
    primary: '#475569',
    secondary: '#64748b',
    background: '#ffffff',
    sidebarBg: '#f8fafc',
    sidebarText: '#475569',
    headerBg: '#475569',
    headerText: '#ffffff',
    text: '#1e293b',
    textLight: '#64748b',
    border: '#cbd5e1',
  },
  burgundy: {
    id: 'burgundy',
    name: 'Burgundy',
    category: 'classic',
    primary: '#7f1d1d',
    secondary: '#991b1b',
    background: '#ffffff',
    sidebarBg: '#fef2f2',
    sidebarText: '#7f1d1d',
    headerBg: '#7f1d1d',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  'dark-green': {
    id: 'dark-green',
    name: 'Dark Green',
    category: 'classic',
    primary: '#14532d',
    secondary: '#166534',
    background: '#ffffff',
    sidebarBg: '#f0fdf4',
    sidebarText: '#14532d',
    headerBg: '#14532d',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
  'royal-blue': {
    id: 'royal-blue',
    name: 'Royal Blue',
    category: 'classic',
    primary: '#1e3a8a',
    secondary: '#2563eb',
    background: '#ffffff',
    sidebarBg: '#eff6ff',
    sidebarText: '#1e3a8a',
    headerBg: '#1e3a8a',
    headerText: '#ffffff',
    text: '#1a1a1a',
    textLight: '#6b7280',
    border: '#d1d5db',
  },
};
