import { StyleSheet } from 'react-native';
import { spacing, fontSize, fontWeight, borderRadius, fontFamily } from '@/utils/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingDescription: {
    marginTop: spacing.md,
    paddingHorizontal: spacing.xl,
    fontSize: fontSize.sm,
    lineHeight: 20,
    textAlign: 'center',
  },
  contentContainer: {
    padding: spacing.md,
    paddingBottom: spacing.xl * 2,
    gap: spacing.lg,
  },
  summaryCard: { gap: spacing.sm },
  summaryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.md,
  },
  summaryTitleBlock: { flex: 1, gap: spacing.xs },
  summarySubtitle: { fontSize: fontSize.sm },
  summaryBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  summaryVerdict: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    marginBottom: spacing.xs,
  },
  summaryBody: { fontSize: fontSize.sm, lineHeight: 20 },
  staleHint: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: spacing.xs,
    marginTop: spacing.sm,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.md,
    borderWidth: StyleSheet.hairlineWidth,
  },
  staleHintText: { fontSize: fontSize.xs, fontWeight: fontWeight.medium },
  metricRow: {
    marginTop: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
  },
  metricBlock: { flex: 1, gap: spacing.xs },
  metricLabel: { fontSize: fontSize.xs, textTransform: 'uppercase' },
  metricValue: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    fontFamily: fontFamily.mono,
  },
  metricDivider: { width: 1, alignSelf: 'stretch', marginHorizontal: spacing.md },
  section: { gap: spacing.sm },
  sectionTitle: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    textTransform: 'uppercase',
  },
  infoGrid: { flexDirection: 'row', gap: spacing.sm },
  infoCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    gap: spacing.xs,
  },
  infoLabel: { fontSize: fontSize.xs, textTransform: 'uppercase' },
  infoValue: { fontSize: fontSize.base, fontWeight: fontWeight.medium },
  badgeWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  helperText: { fontSize: fontSize.sm, lineHeight: 20 },
  helperNumeric: { fontFamily: fontFamily.mono, fontWeight: fontWeight.medium },
  sectionBody: { fontSize: fontSize.sm, lineHeight: 20 },
  schoolHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  schoolTitleBlock: { flex: 1, gap: spacing.xs },
  schoolTitle: { fontSize: fontSize.lg, fontWeight: fontWeight.semibold },
  columnStack: { gap: spacing.sm },
  listCard: { borderWidth: 1, borderRadius: borderRadius.lg, padding: spacing.md, gap: spacing.sm },
  listTitle: { fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  listItem: { flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-start' },
  listItemCompact: { gap: spacing.xs },
  listBullet: { fontSize: fontSize.base, lineHeight: 20 },
  listText: { flex: 1, fontSize: fontSize.sm, lineHeight: 20 },
  evidenceItem: { gap: spacing.xs, paddingVertical: spacing.sm },
  evidenceLabel: { fontSize: fontSize.sm, fontWeight: fontWeight.semibold },
  sourceText: { fontSize: fontSize.xs },
});
