import type { AnalysisSnapshot } from './profile-application-analysis-v2.service';
import { Prisma } from '@prisma/client';

/** Synthetic-only contract fixtures; never production school facts. */
export const segmentExamples = {
  schoolAssessment: {
    summary:
      'The score is below the supplied band; aid eligibility remains unknown.',
    whyThisIsHard: ['The SAT score is below the supplied distribution.'],
    compensatingStrengths: [],
    topGaps: ['Aid eligibility is unknown.'],
    hardStopRisks: [],
    uncertainty: { intervalLabel: 'wide', reasons: ['Aid policy is unknown.'] },
    evidenceIds: ['SYN_E_0'],
    unknowns: ['Aid policy is unknown.'],
  },
  schoolActions: {
    nextActions: ['Confirm aid eligibility before committing.'],
    recourse: {
      goal: 'Confirm feasibility.',
      recommendedChanges: [
        {
          action: 'Confirm aid eligibility.',
          rationale: 'The policy is unknown.',
          effort: 'low',
          timeHorizon: 'now',
          blockedBy: [],
        },
      ],
      estimatedDirection: 'stabilize',
      constraints: ['Aid policy is unknown.'],
      whyNotGuaranteed: 'Admission remains uncertain.',
    },
    evidenceIds: ['SYN_E_0'],
    unknowns: ['Aid policy is unknown.'],
  },
  portfolioAssessment: {
    verdict: 'Add realistic alternatives.',
    balance: 'reachHeavy',
    keyReasons: ['All schools are reaches.'],
    riskBoundaries: ['No academic safety.'],
    unknowns: [],
  },
  portfolioActions: {
    actionPlan: {
      now: ['Research realistic alternatives.'],
      next90Days: [],
      beforeSubmission: [],
    },
    unknowns: [],
  },
};

export function syntheticAnalysisSnapshot(
  count = 1,
  locale = 'en',
): AnalysisSnapshot {
  const timestamp = new Date('2026-08-26T00:00:00Z');
  const schools: AnalysisSnapshot['focusSchools'] = Array.from(
    { length: count },
    (_, i) => ({
      id: `SYN_LIST_${i}`,
      schoolId: `SYN_SCHOOL_${i}`,
      tier: 'REACH',
      tierSource: 'PREDICTED',
      round: 'RD',
      userId: 'SYN_USER',
      notes: null,
      isAIRecommended: false,
      sourceRecommendationId: null,
      createdAt: timestamp,
      updatedAt: timestamp,
      school: {
        id: `SYN_SCHOOL_${i}`,
        name: `Synthetic University ${i}`,
        nameZh: `合成大学${i}`,
        usNewsRank: 50,
        acceptanceRate: new Prisma.Decimal(0.2),
        sat25: 1480,
        sat75: 1550,
        satAvg: 1515,
        testingPolicy: 'REQUIRED',
        testOptional: false,
        needBlindInternational: null,
        intlAcceptanceRate: null,
        metadata: {},
      },
    }),
  );
  return {
    locale,
    analysisVersion: 'synthetic-segments-v1',
    profile: {
      id: 'SYN_PROFILE',
      userId: 'SYN_USER',
      gpa: new Prisma.Decimal(3.7),
      gpaScale: new Prisma.Decimal(4),
      testScores: [
        {
          id: 'SYN_TEST',
          profileId: 'SYN_PROFILE',
          type: 'SAT',
          score: 1420,
          subject: null,
          subScores: null,
          testDate: null,
          createdAt: timestamp,
          updatedAt: timestamp,
        },
      ],
      nickname: null,
      avatarUrl: null,
      bio: null,
      realName: null,
      birthday: null,
      graduationDate: null,
      onboardingCompleted: false,
      weightedGpa: null,
      gpa9: null,
      gpa10: null,
      gpa11: null,
      gpa12: null,
      currentSchool: null,
      currentSchoolType: null,
      regionPref: [],
      educationSystem: null,
      recruitedAthlete: null,
      urmStatus: null,
      applyingTestOptional: null,
      stateOfResidence: null,
      applicationCycleYear: null,
      applicantType: null,
      recruitedSport: null,
      recruitedDivision: null,
      recruitedCoachStatus: null,
      highSchoolId: null,
      recommendationPreferences: null,
      visibility: 'PRIVATE',
      createdAt: timestamp,
      updatedAt: timestamp,
      activities: [],
      awards: [],
      education: [],
      essays: [],
      semesterGpas: [],
      grade: 'SENIOR',
      intendedMajor: 'Computer Science',
      targetMajor: null,
      secondMajor: null,
      nationality: 'CN',
      citizenship: 'CN',
      countryOfResidence: 'CN',
      needsFinancialAid: true,
      firstGeneration: false,
      legacy: [],
      applicationRound: 'RD',
      budgetTier: 'MEDIUM',
    },
    schoolListItems: schools,
    focusSchools: schools,
    predictions: schools.map((s, i) => ({
      id: `SYN_P_${i}`,
      schoolId: s.schoolId,
      probability: new Prisma.Decimal(0.18),
      probabilityLow: new Prisma.Decimal(0.1),
      probabilityHigh: new Prisma.Decimal(0.26),
      tier: 'reach',
      confidence: 'low',
      factors: {},
      suggestions: [],
      confidenceReason: 'Synthetic estimate with unresolved aid policy.',
      applicationRound: 'RD',
      updatedAt: new Date('2026-08-26T00:00:00Z'),
    })),
    approvedEvidence: schools.map((s, i) => ({
      id: `SYN_E_${i}`,
      schoolId: s.schoolId,
      policyDimension: 'TESTING',
      policyValue: 'REQUIRED',
      sourceName: 'Synthetic testing policy',
      sourceUrl: 'https://school.example.invalid/testing',
      sourcePublishedAt: new Date('2026-08-01T00:00:00Z'),
      updatedAt: new Date('2026-08-26T00:00:00Z'),
      metadata: {},
    })),
  };
}
