import type { TemplateDefinition } from '../types';

export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  // ─── Professional (Single Column) ───
  {
    id: 'jake-classic',
    name: 'Jake Classic',
    description: 'The gold-standard single-column ATS resume',
    tags: ['ATS', 'professional', 'single-column'],
    category: 'professional',
    recommendedFor: ['COLLEGE_APPLICATION', 'INTERNSHIP'],
    layout: 'single-column',
    theme: 'black',
    fontPairing: 'helvetica',
    overrides: {
      spacing: {
        page: { x: 36, y: 36 },
        sectionGap: 8,
        itemGap: 5,
        lineHeight: 1.25,
        sidebarWidth: '30%',
      },
      decorations: {
        sectionDivider: 'line',
        headingStyle: 'uppercase',
        bulletStyle: 'disc',
        borderRadius: 0,
        showIcons: false,
        pageSize: 'LETTER',
        dateFormat: 'MMM YYYY',
      },
    },
  },
  {
    id: 'harvard',
    name: 'Harvard',
    description: 'Traditional academic style with Times font',
    tags: ['academic', 'traditional', 'single-column'],
    category: 'academic',
    recommendedFor: ['COLLEGE_APPLICATION'],
    layout: 'single-column',
    theme: 'charcoal',
    fontPairing: 'times',
    overrides: {
      decorations: {
        sectionDivider: 'line',
        headingStyle: 'underline',
        bulletStyle: 'disc',
        borderRadius: 0,
        showIcons: false,
        pageSize: 'LETTER',
        dateFormat: 'MMM YYYY',
      },
    },
  },
  {
    id: 'ivy-league',
    name: 'Ivy League',
    description: 'Dark green accents for a distinguished look',
    tags: ['academic', 'ivy', 'single-column'],
    category: 'academic',
    recommendedFor: ['COLLEGE_APPLICATION'],
    layout: 'single-column',
    theme: 'dark-green',
    fontPairing: 'times',
  },
  {
    id: 'wall-street',
    name: 'Wall Street',
    description: 'Navy professional for finance and business',
    tags: ['professional', 'finance', 'single-column'],
    category: 'professional',
    recommendedFor: ['INTERNSHIP'],
    layout: 'single-column',
    theme: 'navy',
    fontPairing: 'helvetica',
  },
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    description: 'Minimalist grey with Lato font',
    tags: ['minimal', 'clean', 'single-column'],
    category: 'minimal',
    recommendedFor: ['COLLEGE_APPLICATION', 'INTERNSHIP'],
    layout: 'single-column',
    theme: 'slate',
    fontPairing: 'lato',
  },
  {
    id: 'ats-safe',
    name: 'ATS Safe',
    description: 'Maximum ATS compatibility, zero frills',
    tags: ['ATS', 'safe', 'single-column'],
    category: 'professional',
    recommendedFor: ['INTERNSHIP'],
    layout: 'single-column',
    theme: 'black',
    fontPairing: 'helvetica',
    overrides: {
      decorations: {
        sectionDivider: 'line',
        headingStyle: 'uppercase',
        bulletStyle: 'disc',
        borderRadius: 0,
        showIcons: false,
        pageSize: 'LETTER',
        dateFormat: 'MMM YYYY',
      },
    },
  },

  // ─── Modern (Sidebar Left) ───
  {
    id: 'tech-navy',
    name: 'Tech Navy',
    description: 'Modern sidebar layout for tech roles',
    tags: ['modern', 'tech', 'sidebar'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'navy',
    fontPairing: 'roboto',
  },
  {
    id: 'tech-teal',
    name: 'Tech Teal',
    description: 'Fresh teal sidebar for startups',
    tags: ['modern', 'tech', 'sidebar'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'teal',
    fontPairing: 'roboto',
  },
  {
    id: 'creative-indigo',
    name: 'Creative Indigo',
    description: 'Indigo sidebar for design and product roles',
    tags: ['modern', 'creative', 'sidebar'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'indigo',
    fontPairing: 'lato',
  },
  {
    id: 'coral-sidebar',
    name: 'Coral Sidebar',
    description: 'Vibrant coral for marketing and media',
    tags: ['creative', 'marketing', 'sidebar'],
    category: 'creative',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'coral',
    fontPairing: 'lato',
  },
  {
    id: 'violet-edge',
    name: 'Violet Edge',
    description: 'Bold violet for creative industries',
    tags: ['creative', 'bold', 'sidebar'],
    category: 'creative',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'violet',
    fontPairing: 'lato',
  },
  {
    id: 'forest-left',
    name: 'Forest Left',
    description: 'Natural green sidebar for sciences',
    tags: ['professional', 'science', 'sidebar'],
    category: 'professional',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'sidebar-left',
    theme: 'forest',
    fontPairing: 'source-merriweather',
  },
  {
    id: 'rose-elegant',
    name: 'Rose Elegant',
    description: 'Elegant pink sidebar design',
    tags: ['creative', 'elegant', 'sidebar'],
    category: 'creative',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'rose',
    fontPairing: 'source-merriweather',
  },

  // ─── European (Sidebar Right) ───
  {
    id: 'euro-classic',
    name: 'Euro Classic',
    description: 'European-style with right sidebar',
    tags: ['professional', 'european', 'sidebar-right'],
    category: 'professional',
    recommendedFor: ['INTERNSHIP', 'GRADUATE_CV'],
    layout: 'sidebar-right',
    theme: 'charcoal',
    fontPairing: 'helvetica',
  },
  {
    id: 'euro-modern',
    name: 'Euro Modern',
    description: 'Modern European with royal blue accents',
    tags: ['modern', 'european', 'sidebar-right'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-right',
    theme: 'royal-blue',
    fontPairing: 'roboto',
  },

  // ─── Executive (Header Banner Single) ───
  {
    id: 'executive-navy',
    name: 'Executive Navy',
    description: 'Bold navy banner for executive roles',
    tags: ['professional', 'executive', 'banner'],
    category: 'professional',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'header-banner-single',
    theme: 'navy',
    fontPairing: 'helvetica',
  },
  {
    id: 'bold-coral',
    name: 'Bold Coral',
    description: 'Striking coral banner header',
    tags: ['creative', 'bold', 'banner'],
    category: 'creative',
    recommendedFor: ['INTERNSHIP'],
    layout: 'header-banner-single',
    theme: 'coral',
    fontPairing: 'roboto',
  },
  {
    id: 'amber-banner',
    name: 'Amber Banner',
    description: 'Warm amber banner header',
    tags: ['creative', 'warm', 'banner'],
    category: 'creative',
    recommendedFor: ['INTERNSHIP'],
    layout: 'header-banner-single',
    theme: 'amber',
    fontPairing: 'lato',
  },

  // ─── Dense (Header Banner Columns) ───
  {
    id: 'dense-navy',
    name: 'Dense Navy',
    description: 'Navy banner with two-column body for max info',
    tags: ['professional', 'dense', 'columns'],
    category: 'professional',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'header-banner-columns',
    theme: 'navy',
    fontPairing: 'helvetica',
  },
  {
    id: 'dense-teal',
    name: 'Dense Teal',
    description: 'Teal banner with two-column body',
    tags: ['modern', 'dense', 'columns'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'header-banner-columns',
    theme: 'teal',
    fontPairing: 'roboto',
  },

  // ─── Equal Columns ───
  {
    id: 'dual-classic',
    name: 'Dual Classic',
    description: 'Equal two-column with traditional style',
    tags: ['professional', 'dual', 'columns'],
    category: 'professional',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'equal-columns',
    theme: 'charcoal',
    fontPairing: 'times',
  },
  {
    id: 'dual-modern',
    name: 'Dual Modern',
    description: 'Equal two-column with modern indigo',
    tags: ['modern', 'dual', 'columns'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'equal-columns',
    theme: 'indigo',
    fontPairing: 'lato',
  },

  // ─── Timeline ───
  {
    id: 'timeline-slate',
    name: 'Timeline Slate',
    description: 'Narrative timeline with slate accents',
    tags: ['creative', 'timeline', 'narrative'],
    category: 'creative',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'timeline',
    theme: 'slate',
    fontPairing: 'lato',
  },
  {
    id: 'timeline-navy',
    name: 'Timeline Navy',
    description: 'Professional timeline with navy dots',
    tags: ['professional', 'timeline'],
    category: 'professional',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'timeline',
    theme: 'navy',
    fontPairing: 'helvetica',
  },

  // ─── Academic ───
  {
    id: 'academic-burgundy',
    name: 'Academic Burgundy',
    description: 'Classic academic CV in burgundy',
    tags: ['academic', 'burgundy', 'single-column'],
    category: 'academic',
    recommendedFor: ['GRADUATE_CV'],
    layout: 'single-column',
    theme: 'burgundy',
    fontPairing: 'times',
  },

  // ─── Chinese ───
  {
    id: 'chinese-classic',
    name: '\u4E2D\u6587\u7ECF\u5178',
    description: 'Classic Chinese resume with Noto Sans SC',
    tags: ['chinese', 'professional', 'single-column'],
    category: 'professional',
    recommendedFor: ['COLLEGE_APPLICATION', 'INTERNSHIP'],
    layout: 'single-column',
    theme: 'black',
    fontPairing: 'noto-sans-sc',
  },
  {
    id: 'chinese-modern',
    name: '\u4E2D\u6587\u73B0\u4EE3',
    description: 'Modern Chinese resume with sidebar',
    tags: ['chinese', 'modern', 'sidebar'],
    category: 'modern',
    recommendedFor: ['INTERNSHIP'],
    layout: 'sidebar-left',
    theme: 'indigo',
    fontPairing: 'noto-sans-sc',
  },
];
