import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import type { AIAnalysisResult } from '@study-abroad/shared';

// 注册中文字体
Font.register({
  family: 'Noto Sans SC',
  fonts: [
    {
      src: 'https://fonts.gstatic.com/s/notosanssc/v36/k3kCo84MPvpLmixcA63oeAL7Iqp5IZJF9bmaG9_FnYxNbPzS5HE.ttf',
      fontWeight: 400,
    },
    {
      src: 'https://fonts.gstatic.com/s/notosanssc/v36/k3kCo84MPvpLmixcA63oeAL7Iqp5IZJF9bmaG9_EnYxNbPzS5HE.ttf',
      fontWeight: 700,
    },
  ],
});

interface AnalysisReportPDFProps {
  data: AIAnalysisResult;
  locale: 'zh' | 'en';
}

const colors = {
  primary: '#6366f1',
  secondary: '#8b5cf6',
  text: '#1f2937',
  textMuted: '#6b7280',
  border: '#e5e7eb',
  background: '#f9fafb',
  success: '#10b981',
  successBg: '#ecfdf5',
  warning: '#f59e0b',
  warningBg: '#fffbeb',
  white: '#ffffff',
};

const translations = {
  zh: {
    title: '申请分析报告',
    subtitle: '结构化顾问视图',
    generatedAt: '生成时间',
    overallScore: '综合评分',
    overview: '综合分析',
    strengths: '补偿优势',
    weaknesses: '主要风险',
    improvements: '当前行动',
    activities: '补充建议',
    timeline: '分阶段计划',
    disclaimer: '本报告由 AI 自动生成，仅供参考。实际申请结果可能与预测有差异。',
  },
  en: {
    title: 'Application Analysis Report',
    subtitle: 'Structured strategy view',
    generatedAt: 'Generated at',
    overallScore: 'Overall Score',
    overview: 'Overview',
    strengths: 'Compensating Strengths',
    weaknesses: 'Main Risks',
    improvements: 'Immediate Actions',
    activities: 'Supplemental Recommendations',
    timeline: 'Phased Plan',
    disclaimer:
      'This report is generated by AI and is for reference only. Actual results may vary.',
  },
};

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Noto Sans SC',
    fontSize: 10,
    color: colors.text,
    backgroundColor: colors.white,
  },
  // Header
  header: {
    marginBottom: 24,
    borderBottom: `2px solid ${colors.primary}`,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: colors.primary,
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 10,
    color: colors.textMuted,
  },
  headerDate: {
    fontSize: 9,
    color: colors.textMuted,
    marginTop: 6,
  },
  // Score section
  scoreSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    marginBottom: 20,
    backgroundColor: '#f0f0ff',
    borderRadius: 8,
    border: `1px solid ${colors.primary}`,
  },
  scoreLabel: {
    fontSize: 11,
    color: colors.textMuted,
    marginBottom: 4,
  },
  scoreValue: {
    fontSize: 32,
    fontWeight: 700,
    color: colors.primary,
  },
  scoreMax: {
    fontSize: 14,
    color: colors.textMuted,
  },
  potentialBadge: {
    backgroundColor: '#ecfdf5',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    border: `1px solid ${colors.success}`,
  },
  potentialText: {
    fontSize: 11,
    fontWeight: 700,
    color: colors.success,
  },
  // Section
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: colors.text,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottom: `1px solid ${colors.border}`,
  },
  // Overview
  overviewText: {
    fontSize: 10,
    lineHeight: 1.6,
    color: colors.text,
  },
  // List items
  listItem: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingLeft: 4,
  },
  bulletStrength: {
    color: colors.success,
    fontSize: 12,
    marginRight: 8,
    width: 12,
  },
  bulletWeakness: {
    color: colors.warning,
    fontSize: 12,
    marginRight: 8,
    width: 12,
  },
  bulletImprovement: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: 700,
    marginRight: 8,
    width: 16,
  },
  bulletActivity: {
    color: colors.secondary,
    fontSize: 10,
    marginRight: 8,
    width: 12,
  },
  listText: {
    fontSize: 10,
    lineHeight: 1.5,
    flex: 1,
    color: colors.text,
  },
  // Strengths/Weaknesses row
  swContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  swColumn: {
    flex: 1,
  },
  strengthBox: {
    padding: 10,
    backgroundColor: colors.successBg,
    borderRadius: 6,
    border: `1px solid #a7f3d0`,
  },
  weaknessBox: {
    padding: 10,
    backgroundColor: colors.warningBg,
    borderRadius: 6,
    border: `1px solid #fde68a`,
  },
  boxTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
  },
  strengthTitle: {
    color: '#047857',
  },
  weaknessTitle: {
    color: '#b45309',
  },
  // Timeline
  timelineRow: {
    flexDirection: 'row',
    marginBottom: 6,
    alignItems: 'flex-start',
  },
  timelineDate: {
    fontSize: 10,
    fontWeight: 700,
    color: colors.primary,
    width: 80,
  },
  timelineTask: {
    fontSize: 10,
    color: colors.text,
    flex: 1,
  },
  // Footer
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: `1px solid ${colors.border}`,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 8,
    color: colors.textMuted,
    textAlign: 'center',
  },
});

/**
 * 简单 Markdown → 纯文本
 * 去掉 #, **, *, -, > 等标记，保留文字内容
 */
function stripMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s+/gm, '') // headings
    .replace(/\*\*(.+?)\*\*/g, '$1') // bold
    .replace(/\*(.+?)\*/g, '$1') // italic
    .replace(/^[-*+]\s+/gm, '• ') // list markers → bullet
    .replace(/^\d+\.\s+/gm, '') // numbered lists
    .replace(/^>\s+/gm, '') // blockquote
    .replace(/`(.+?)`/g, '$1') // inline code
    .replace(/\[(.+?)\]\(.+?\)/g, '$1') // links → text
    .trim();
}

export function AnalysisReportPDF({ data, locale }: AnalysisReportPDFProps) {
  const t = translations[locale] || translations.zh;
  const now = new Date().toLocaleString(locale === 'zh' ? 'zh-CN' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const overviewText = stripMarkdown(
    [data.portfolioSummary.verdict, ...data.portfolioSummary.keyReasons]
      .filter(Boolean)
      .join('\n\n')
  );
  const strengths =
    data.schools.flatMap((school) => school.assessment.compensatingStrengths).slice(0, 6) ?? [];
  const weaknesses =
    data.schools
      .flatMap((school) => [...school.assessment.topGaps, ...school.assessment.hardStopRisks])
      .slice(0, 6) ?? [];
  const improvements = data.actionPlan.now ?? [];
  const recommendedActivities = [
    ...data.schools.flatMap((school) => school.assessment.nextActions),
    ...data.unknowns,
  ].slice(0, 8);
  const timeline = [
    {
      date: locale === 'zh' ? '现在' : 'Now',
      tasks: data.actionPlan.now ?? [],
    },
    {
      date: locale === 'zh' ? '未来 90 天' : 'Next 90 days',
      tasks: data.actionPlan.next90Days ?? [],
    },
    {
      date: locale === 'zh' ? '提交前' : 'Before submission',
      tasks: data.actionPlan.beforeSubmission ?? [],
    },
  ].filter((group) => group.tasks.length > 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>{t.title}</Text>
          <Text style={styles.headerSubtitle}>{t.subtitle}</Text>
          <Text style={styles.headerDate}>
            {t.generatedAt}: {now}
          </Text>
        </View>

        {/* Score */}
        <View style={styles.scoreSection}>
          <View>
            <Text style={styles.scoreLabel}>{t.overallScore}</Text>
            <View style={{ flexDirection: 'row', alignItems: 'flex-end' }}>
              <Text style={styles.scoreValue}>{data.schools.length}</Text>
              <Text style={styles.scoreMax}> schools</Text>
            </View>
          </View>
          <View style={styles.potentialBadge}>
            <Text style={styles.potentialText}>{data.meta?.state ?? 'ready'}</Text>
          </View>
        </View>

        {/* Overview */}
        {overviewText && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t.overview}</Text>
            <Text style={styles.overviewText}>{overviewText}</Text>
          </View>
        )}

        {/* Strengths & Weaknesses side by side */}
        {(strengths.length > 0 || weaknesses.length > 0) && (
          <View style={styles.swContainer}>
            {/* Strengths */}
            <View style={styles.swColumn}>
              <View style={styles.strengthBox}>
                <Text style={[styles.boxTitle, styles.strengthTitle]}>✓ {t.strengths}</Text>
                {strengths.map((s, i) => (
                  <View key={i} style={styles.listItem}>
                    <Text style={styles.bulletStrength}>•</Text>
                    <Text style={styles.listText}>{s}</Text>
                  </View>
                ))}
              </View>
            </View>
            {/* Weaknesses */}
            <View style={styles.swColumn}>
              <View style={styles.weaknessBox}>
                <Text style={[styles.boxTitle, styles.weaknessTitle]}>! {t.weaknesses}</Text>
                {weaknesses.map((w, i) => (
                  <View key={i} style={styles.listItem}>
                    <Text style={styles.bulletWeakness}>•</Text>
                    <Text style={styles.listText}>{w}</Text>
                  </View>
                ))}
              </View>
            </View>
          </View>
        )}

        {/* Improvements */}
        {improvements.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t.improvements}</Text>
            {improvements.map((item, i) => (
              <View key={i} style={styles.listItem}>
                <Text style={styles.bulletImprovement}>{i + 1}.</Text>
                <Text style={styles.listText}>{item}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Recommended Activities */}
        {recommendedActivities.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t.activities}</Text>
            {recommendedActivities.map((activity, i) => (
              <View key={i} style={styles.listItem}>
                <Text style={styles.bulletActivity}>★</Text>
                <Text style={styles.listText}>{activity}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Timeline */}
        {timeline.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>{t.timeline}</Text>
            {timeline.map((group, i) => (
              <View key={i} style={{ marginBottom: 8 }}>
                <View style={styles.timelineRow}>
                  <Text style={styles.timelineDate}>{group.date}</Text>
                  <Text style={styles.timelineTask}>{group.tasks.join('； ')}</Text>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* Footer */}
        <View style={styles.footer}>
          <Text style={styles.footerText}>{t.disclaimer}</Text>
        </View>
      </Page>
    </Document>
  );
}
